01_07_001b02:commit

diff --git a/trunk/ctys/bin/ctys-wakeup b/trunk/ctys/bin/ctys-wakeup
--- a/trunk/ctys/bin/ctys-wakeup
+++ b/trunk/ctys/bin/ctys-wakeup
@@ -59,7 +59,7 @@ LICENCE=GPL3
 #  bash-script
 #
 #VERSION:
-VERSION=01_01_001a02
+VERSION=01_07_001b02
 #DESCRIPTION:
 #  Sends a magic packet to:
 #
@@ -122,6 +122,8 @@ shopt -s nullglob
 ################################################################
 #       System definitions - do not change these!              #
 ################################################################
+
+C_EXECLOCAL=1;
 
 #Execution anchor
 MYHOST=`uname -n`
@@ -315,6 +317,7 @@ TARGET_WM_FORESEEN="KDE(might work now)"
 #
 case ${MYOS} in
     Linux);;
+    OpenBSD);;
     *)
         printINFO 1 $LINENO $BASH_SOURCE 1 "${MYCALLNAME} is not supported on ${MYOS}"
 	gotoHell 0
@@ -323,6 +326,7 @@ esac
 
 . ${MYLIBPATH}/lib/help/help
 . ${MYLIBPATH}/lib/security
+. ${MYLIBPATH}/lib/network/network
 
 #path to directory containing the default mapping db
 if [ -d "${HOME}/.ctys/db/default" ];then
@@ -334,6 +338,20 @@ if [ -d "${MYCONFPATH}/db/default" ];then
     DEFAULT_DBPATHLST=${DEFAULT_DBPATHLST:-$HOME/conf/db/default}
 fi
 
+
+if [ -d "${HOME}/.ctys" -a -d "${HOME}/.ctys/pm" ];then
+    #Source pre-set environment from user
+    if [ -f "${HOME}/.ctys/pm/pm.conf.${MYOS}" ];then
+	. "${HOME}/.ctys/pm/pm.conf.${MYOS}"
+    fi
+fi
+
+if [ -d "${MYCONFPATH}/pm" ];then
+    #Source pre-set environment from installation 
+    if [ -f "${MYCONFPATH}/pm/pm.conf.${MYOS}" ];then
+	. "${MYCONFPATH}/pm/pm.conf.${MYOS}"
+    fi
+fi
 
 #Source pre-set environment from user
 if [ -f "${HOME}/.ctys/ctys.conf" ];then
@@ -441,27 +459,32 @@ function buildWOLMagicPacket () {
 function remoteWOL () {
     local _dbg1=${C_DARGS:+ -v }
     local _wait=2
+
+    if [ -z "${CTYS_NETCAT0}" ];then
+	ABORT=1;
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Requires a CTYS_NETCAT0=netcat/nc version."
+	gotoHell ${ABORT}
+    fi
+
     if [ -n "$_tcp" ];then
 	if [ -z "$_noexe" ];then
-            _call="buildWOLMagicPacket $_mac;echo \"|nc $_dbg1 -u -w $_wait 255.255.255.255 $_port\""
-
-            _call="printf \"`buildWOLMagicPacket $_mac`\n\"|nc $_dbg1 -u -w $_wait $_tcp $_port"
+            _call="printf \"`buildWOLMagicPacket $_mac`\"|${CTYS_NETCAT0} $_dbg1 -u -w $_wait $_tcp $_port"
 	    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "$_call"
 
-	    printf "`buildWOLMagicPacket $_mac`\n"|nc $_dbg1 -u -w $_wait $_tcp $_port
+	    printf "`buildWOLMagicPacket $_mac`"|${CTYS_NETCAT0} $_dbg1 -u -w $_wait $_tcp $_port
 	    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "=>$?"
 	else
-	    buildWOLMagicPacket $_mac;echo "|nc $_dbg1 -u -w $_wait $_tcp $_port"
+	    buildWOLMagicPacket $_mac;echo -n -e "|${CTYS_NETCAT0} $_dbg1 -u -w $_wait $_tcp $_port"
 	fi
     else
 	if [ -z "$_noexe" ];then
-            _call="printf \"`buildWOLMagicPacket $_mac`\n\"|nc $_dbg1 -u -w $_wait  255.255.255.255 $_port"
+            _call="printf \"`buildWOLMagicPacket $_mac`\n\"|${CTYS_NETCAT0} $_dbg1 -u -w $_wait  255.255.255.255 $_port"
 	    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "$_call"
 
-	    printf "`buildWOLMagicPacket $_mac`\n"|nc $_dbg1 -u -w $_wait 255.255.255.255 $_port
+	    printf "`buildWOLMagicPacket $_mac`"|${CTYS_NETCAT0} $_dbg1 -u -w $_wait 255.255.255.255 $_port
 	    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "=>$?"
 	else
-	    buildWOLMagicPacket $_mac;echo "|nc $_dbg1 -u -w $_wait 255.255.255.255 $_port"
+	    buildWOLMagicPacket $_mac;echo -n -e "|${CTYS_NETCAT0} $_dbg1 -u -w $_wait 255.255.255.255 $_port"
 	fi
     fi
 }
@@ -472,29 +495,52 @@ function localWOL () {
     local _dbg1=${C_DARGS:+ -D }
     local _ret=0;
 
-    CTYS_WOL_LOCAL=`getPathName $LINENO $BASH_SOURCE ERROR ether-wake /sbin`
+    #an actual ethernet frame only
+    function useEtherWake (){
+	local PMCALL=;
+	checkedSetSUaccess  "${_myHint}" PMCALL   CTYS_WOL_LOCAL  -i lo 11:22:33:44:55:66
+	if [ $? -eq 0 ];then
+	    CTYS_WOL_LOCAL="$PMCALL $CTYS_WOL_LOCAL"
+	else
+	    CTYS_WOL_LOCAL="echo \"Missing permission in $BASH_SOURCE:$LINENO->$PMCALL $CTYS_WOL_LOCAL\";gotoHell 1;"
+	fi
+	CTYS_WOL_LOCAL_WAKEUP="$CTYS_WOL_LOCAL"
+	printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL=$CTYS_WOL_LOCAL"
+	printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL_WAKEUP=$CTYS_WOL_LOCAL_WAKEUP"
 
-    local PMCALL=;
-    checkedSetSUaccess  "${_myHint}" PMCALL   CTYS_WOL_LOCAL  -i lo 11:22:33:44:55:66
-    if [ $? -eq 0 ];then
-	CTYS_WOL_LOCAL="$PMCALL $CTYS_WOL_LOCAL"
+	CTYS_WOL_LOCAL_WAKEUP="${CTYS_WOL_LOCAL} $_dbg1 -b -i ${_if} $_mac"
+
+	printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "${CTYS_WOL_LOCAL_WAKEUP}"
+	${CTYS_WOL_LOCAL_WAKEUP}
+	_ret=$?
+	printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "=>$_ret"   
+    }
+
+    #a UDP broadcast, same as remoteWOL, thus use own script
+    function useWOL (){
+	local PMCALL=;
+	checkedSetSUaccess  "${_myHint}" PMCALL   CTYS_WOL_LOCAL  -V >/dev/null
+	if [ $? -eq 0 ];then
+	    CTYS_WOL_LOCAL="$PMCALL $CTYS_WOL_LOCAL"
+	else
+	    CTYS_WOL_LOCAL="echo \"Missing permission in $BASH_SOURCE:$LINENO->$PMCALL $CTYS_WOL_LOCAL\";gotoHell 1;"
+	fi
+	CTYS_WOL_LOCAL_WAKEUP="${CTYS_WOL_LOCAL} $_mac"
+	printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL=$CTYS_WOL_LOCAL"
+	printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL_WAKEUP=$CTYS_WOL_LOCAL_WAKEUP"
+	${CTYS_WOL_LOCAL_WAKEUP}
+	_ret=$?
+	printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "=>$_ret"   
+    }
+
+    if [ "${CTYS_WOL_LOCAL//wol/}" == "${CTYS_WOL_LOCAL}" ];then
+	useEtherWake
     else
-	CTYS_WOL_LOCAL="echo \"Missing permission in $BASH_SOURCE:$LINENO->$PMCALL $CTYS_WOL_LOCAL\";gotoHell 1;"
+#	remoteWOL
+	useWOL
     fi
-#    CTYS_WOL_WAKEUP_LOCAL="$PMCALL $CTYS_WOL_WAKEUP"
-    CTYS_WOL_LOCAL_WAKEUP="$CTYS_WOL_LOCAL"
-    printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL=$CTYS_WOL_LOCAL"
-    printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME CTYS_WOL_LOCAL_WAKEUP=$CTYS_WOL_LOCAL_WAKEUP"
 
 
-
-
-    CTYS_WOL_LOCAL_WAKEUP="${CTYS_WOL_LOCAL} $_dbg1 -b -i ${_if} $_mac"
-
-    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "${CTYS_WOL_LOCAL_WAKEUP}"
-    ${CTYS_WOL_LOCAL_WAKEUP}
-    _ret=$?
-    printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "=>$_ret"   
 }
 
 
diff --git a/trunk/ctys/plugins/VMs/QEMU/session b/trunk/ctys/plugins/VMs/QEMU/session
--- a/trunk/ctys/plugins/VMs/QEMU/session
+++ b/trunk/ctys/plugins/VMs/QEMU/session
@@ -8,16 +8,16 @@
 #SHORT:        ctys
 #CALLFULLNAME: Commutate To Your Session
 #LICENCE:      GPL3
-#VERSION:      01_02_007a17
+#VERSION:      01_07_001b02
 #
 ########################################################################
 #
-# Copyright (C) 2007 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
+# Copyright (C) 2007,2008 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
 #
 ########################################################################
 
 _myPKGNAME_QEMU_SESSION="${BASH_SOURCE}"
-_myPKGVERS_QEMU_SESSION="01.01.001a00pre"
+_myPKGVERS_QEMU_SESSION="01.07.001b02"
 hookInfoAdd $_myPKGNAME_QEMU_SESSION $_myPKGVERS_QEMU_SESSION
 _myPKGBASE_QEMU_SESSION="`dirname ${_myPKGNAME_QEMU_SESSION}`"
 
@@ -281,6 +281,8 @@ function startSessionQEMU () {
   case ${QEMU_MAGIC} in
       QEMU_091) #verified to work
 	  ;;
+      QEMU_090) #verified to work
+	  ;;
       QEMU_09x)
 	  printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:This version is not yet tested, but any version \"0.9.x\" might work."
 	  printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:  QEMU_VERSTRING = ${QEMU_VERSTRING}"
@@ -297,6 +299,7 @@ function startSessionQEMU () {
   #use these in wrapper config scripts: _pname
   export QEMUCALL
   export QEMU
+  export QEMU_MAGIC
 
 
   #set appropriate call
@@ -706,11 +709,24 @@ function vmMgrQEMU () {
 	gotoHell ${ABORT}
     fi
 
-    if [ ! -S "${_sport}" ];then
+    if [ ! -e "${_sport}" ];then
 	ABORT=1;
-	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Cannot access UNIX-Domain socket:SPORT=${_sport}"
-	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Continue, but use \"stackerCancelPropagate\" and/or \"kill\" from now on."
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Missing UNIX-Domain socket:"
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:  SPORT=${_sport}"
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Probably a prevoious \"stackerCancelPropagate\""
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:was meanwhile successful."
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Continue, but use \"kill\" from now on if"
+	printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:FORCE is set."
 	_sport=;
+    else
+	if [ ! -S "${_sport}" ];then
+	    ABORT=1;
+	    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Cannot access SPORT, Is not a UNIX-Domain socket:"
+	    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:  SPORT=${_sport}"
+	    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Continue, but use \"kill\" from now on if"
+	    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:FORCE is set."
+	    _sport=;
+	fi
     fi
 
     function callMonitorCmd () {
@@ -718,6 +734,16 @@ function vmMgrQEMU () {
         local _monsock=$1;shift
         local _cmd=$*
 	printDBG $S_QEMU ${D_FLOW} $LINENO $BASH_SOURCE "${FUNCNAME} monsock=<${_monsock}> cmd=<${_cmd}>"
+
+	checkConsole "${_monsock}"
+	local _ret=$?;
+	if [ $_ret -ne 0 ];then
+	    printWNG 1 $LINENO $BASH_SOURCE 1 "${FUNCNAME}:Cannot acces MONSOCK=<${_monsock}>"
+	    printWNG 1 $LINENO $BASH_SOURCE 1 "${FUNCNAME}:In use:users=$((_ret-1))"
+	    printDBG $S_QEMU ${D_FLOW} $LINENO $BASH_SOURCE "${FUNCNAME}:Cannot acces MOSOCK=<${_monsock}>"
+	    printDBG $S_QEMU ${D_FLOW} $LINENO $BASH_SOURCE "${FUNCNAME}:In use:users=$((_ret-1))"
+	    return 1
+	fi
 
 	if [ -n "${CTYS_NETCAT}" ];then
 	    local _call="echo -e -n '\001\143${_cmd}\n\001\143'|${QEMUCALL} ${CTYS_NETCAT} -U ${_monsock}"
@@ -737,6 +763,7 @@ EOF
     }
 
 
+    releaseConsole "${_sport}"
     case $_cmd in
         #CREATE######################
 	RS3|PAUSE)
@@ -802,12 +829,21 @@ EOF
             if [ -z "${C_NOEXEC}" ];then
 		if [ -n "${_sport}" ];then
 		    callMonitorCmd "${_sport}" '\001\170\n'
+		    if [ $? -ne 0 ];then
+			ABORT=1
+			printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Cannot POWEROFF native GuestOS"
+			if [ "$_arg2" != FORCE ];then
+			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Stop running client, and/or use the \"FORCE\" Luke."
+			fi
+		    fi
 		else
 		    ABORT=1;
-		    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Cannot submit command:${_cmd}"
+		    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Missing SPORT, Cannot submit command:${_cmd}"
 		fi
 		case "$_arg2" in
 		    FORCE)
+
+
 			ABORT=1;
 			_timeout=${_arg1:-1}
 			printINFO 1 $LINENO $BASH_SOURCE $ABORT "${FUNCNAME} Delay forced kill:${_timeout} seconds"
@@ -836,8 +872,11 @@ EOF
 			;;
 		    *)
 			if [ -z "${_sport}" ];then
-			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Use FORCE flag for ultimative kill."
-			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Be aware, that this is an \"actual-switch-off\" ."
+			    ABORT=1;
+			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:If VM is still present use of the FORCE Luke"
+			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:Be aware, that this is an actual and abrupt"
+			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:\"switch-off\" by \"kill\" of the QEMU processes"
+			    printWNG 1 $LINENO $BASH_SOURCE ${ABORT} "$FUNCNAME:which could eventually damage the the GuestOS."
 			fi
 			;;
 		esac
