01_07_001a01:commit

diff --git a/trunk/ctys/bin/ctys-install b/trunk/ctys/bin/ctys-install
--- a/trunk/ctys/bin/ctys-install
+++ b/trunk/ctys/bin/ctys-install
@@ -1,3 +1,33 @@
+########################################################################
+#
+#PROJECT:      Unified Sessions Manager
+#AUTHOR:       Arno-Can Uestuensoez - acue@UnifiedSessionsManager.org
+#MAINTAINER:   Arno-Can Uestuensoez - acue_sf1@sourceforge.net
+#SHORT:        ctys
+#CALLFULLNAME: Commutate To Your Session
+#LICENCE:      GPL3
+#VERSION:      01_06_001a15
+#
+########################################################################
+#
+#     Copyright (C) 2007,2008 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
+#
+#     This program is free software: you can redistribute it and/or modify
+#     it under the terms of the GNU General Public License as published by
+#     the Free Software Foundation, either version 3 of the License, or
+#     (at your option) any later version.
+#
+#     This program is distributed in the hope that it will be useful,
+#     but WITHOUT ANY WARRANTY; without even the implied warranty of
+#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#     GNU General Public License for more details.
+#
+#     You should have received a copy of the GNU General Public License
+#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+########################################################################
+
+
 #FUNCEG###############################################################
 #
 #PROJECT:
@@ -22,7 +52,7 @@ LICENCE=GPL3
 #  sh-script
 #
 #VERSION:
-VERSION=01_01_001b04
+VERSION=01_06_001A15
 #DESCRIPTION:
 #  Install script for ctys. Generic shell script for bootstrap, 
 #  should work on almost any bourne-like shell.
@@ -59,6 +89,53 @@ VERSION=01_01_001b04
 #
 #FUNCEND###############################################################
 
+MYOS=`dirname $0`
+MYOS=`${MYOS}/getCurOS`
+
+
+if [ -z "$BASH" ];then
+    echo "*********************************************************************"
+    echo "* The UnifiedSessionsManager scripts require the \"bash\".            *"
+    echo "* For the installation of this version a user driven setting of the *"
+    echo "* \"bash\" shell is required.                                         *"
+    echo "*                                                                   *"
+    echo "* Call: 1. bash                                                     *"
+    echo "*       2. <path>/ctys-install <args>                               *"
+    echo "*                                                                   *"
+    echo "*********************************************************************"
+    exit 1
+fi
+
+
+if [ "$HOME" == "/" ];then
+    echo "The UnifiedSessionsManager requires a HOME directory differen from top=\"/\"."
+    echo "If you are root, you may create \"/root\" and set this as your home."
+    exit 1
+fi
+
+case ${MYOS} in
+    SunOS)
+	export PATH=/usr/xpg4/bin:/opt/sfw/bin:/usr/sbin:/usr/bin:/usr/openwin/bin:$PATH
+	;;
+esac
+
+function gwhich () {
+    case ${MYOS} in
+	SunOS)
+	    local _xf=`which $*`;
+	    case $_xf in
+		no*)
+		    return 1;
+		    ;;
+	    esac
+	    echo -n -e $_xf
+	    ;;
+	*)which $*
+	    ;;
+    esac
+}
+
+
 if [ "${*}" != "`echo ${*}|sed 's/-h//'`" ];then
     dn=`dirname $0`
     ${dn}/ctys-install1 -h
@@ -66,10 +143,10 @@ if [ "${*}" != "`echo ${*}|sed 's/-h//'`" ];then
 fi
 
 if [ "${*}" != "`echo ${*}|sed 's/-X//'`" ];then
-    CTRL_TERSE=1
+    C_TERSE=1
 fi
 if [ "${*}" != "`echo ${*}|sed 's/-V//'`" ];then
-    if [ -n "${CTRL_TERSE}" ];then
+    if [ -n "${C_TERSE}" ];then
 	echo -n ${VERSION}
     else
 	echo "$0: VERSION=${VERSION}"
@@ -91,13 +168,13 @@ echo
 ######################################################################
 
 #mandatory-0
-MANDATORY="which bash dirname basename find grep awk sleep "
+MANDATORY="which bash dirname basename find grep awk sleep uname "
 echo "Check for level-0==absolutely-mandatory - else almost nothing might work."
 for i in $MANDATORY;do
-    CHK=`which $i 2>&1 >/dev/null`
-    if [ $? != 0 ];then
+    gwhich $i 2>&1 >/dev/null
+    if [ $? -ne 0 ];then
 	echo "Oh, ...."
-	echo "....missing level-0==absolutely-mandatory:\"$i\", so check your basic shell evironment."
+ 	echo "....missing level-0==absolutely-mandatory:\"$i\", so check your basic shell evironment."
 	exit 1
     else
 	echo "      $i - OK"
@@ -106,11 +183,11 @@ done
 echo
 
 #mandatory-1
-MANDATORY="ps"
+MANDATORY="ps "
 echo "Check fof level-1==mandatory - else (for now too!) almost nothing might work."
 for i in $MANDATORY;do
-    CHK=`which $i 2>&1 >/dev/null`
-    if [ $? != 0 ];then
+    gwhich $i 2>&1 >/dev/null
+    if [ $? -ne 0 ];then
 	echo "Oh, ...."
 	echo "....missing level-1==mandatory:\"$i\", so check your basic shell evironment."
 	echo "....you might be probably operating within a restricted-shell."
@@ -123,20 +200,23 @@ echo
 
 #mandatory-2
 MANDATORY="vncserver vncviewer"
-echo "Check fof level-2==mandatory - else (for now too!) no remote-desktops."
+echo "Check of level-2==mandatory - else (for now too!) no remote-desktops."
 for i in $MANDATORY;do
-    CHK=`which $i 2>&1 >/dev/null`
-    if [ $? != 0 ];then
+    gwhich $i 2>&1 >/dev/null
+    if [ $? -ne 0 ];then
 	echo "Oh, ...."
-	echo "....missing level-1==mandatory:\"$i\", so check your basic shell evironment."
-	echo "....you do at least require \"vncserver\" for \"ConnectionForwarding\"."
+	echo "....missing level-2==mandatory:\"$i\", so check your basic shell evironment."
+	echo "....you do at least require \"vncserver\" for \"CONNECTIONFORWARDING\"."
 	echo "....\"TightVNC\" or \"RealVNC\""
-	exit 1
+
+	echo "Anyhow, for now continue."
+#	exit 1
     else
 	echo "      $i - OK"
     fi
 done
 echo
+
 
 
 #by convention: CURCALLDIR=$CURINSTTREE/bin
@@ -146,8 +226,8 @@ CURINSTCONF=${CURINSTTREE}/conf/ctys
 
 MANDATORY="${CURCALLDIR}/ctys-install1"
 for i in $MANDATORY;do
-    CHK=`which $i 2>&1 >/dev/null`
-    if [ $? != 0 ];then
+    gwhich $i 2>&1 >/dev/null
+    if [ $? -ne 0 ];then
 	echo "Oh, ...."
 	echo "....missing \"$i\", so check your basic shell evironment."
 	exit 1
@@ -161,36 +241,39 @@ echo
 echo "Setting distribution."
 echo
 CUROS=`${CURCALLDIR}/getCurOS`;
-echo "   CUROS   = ${CUROS}"
+echo "   CUROS      = ${CUROS}"
 
-CURREL=`${CURCALLDIR}/getCurRelease`;
-echo "   CURREL  = ${CURREL}"
+CUROSREL=`${CURCALLDIR}/getCurOSRel`;
+echo "   CUROSREL   = ${CUROSREL}"
 
 CURDIST=`${CURCALLDIR}/getCurDistribution`;
-echo "   CURDIST = ${CURDIST}"
+echo "   CURDIST    = ${CURDIST}"
+
+CURREL=`${CURCALLDIR}/getCurRelease`;
+echo "   CURREL     = ${CURREL}"
 
 
 echo
-######################################################################
-echo
-echo "  - Switch \"systools.conf\""
-echo
-######################################################################
-echo
-echo "    Current OS-REL=${CUROS}-${CURREL}"
-echo "     =>${CURINSTCONF}/systools.conf.${CURDIST}"
-echo
-if [ ! -f "${CURINSTCONF}/systools.conf.${CURDIST}" ];then
-   echo "Missing: ${CURINSTCONF}/systools.conf.${CURDIST}"
-   exit 1
-fi
+# ######################################################################
+# echo
+# echo "  - Switch \"systools.conf.${MYDIST}\""
+# echo
+# ######################################################################
+# echo
+# echo "    Current OS-REL=${CUROS}-${CURREL}"
+# echo "     =>${CURINSTCONF}/systools.conf.${MYDIST}.${CURDIST}"
+# echo
+# if [ ! -f "${CURINSTCONF}/systools.conf.${MYDIST}.${CURDIST}" ];then
+#    echo "Missing: ${CURINSTCONF}/systools.conf.${MYDIST}.${CURDIST}"
+#    exit 1
+# fi
 
-###########
-#REMARK:
-#  Do this for a short migration time of legacy only, threafter
-#  use seamlessly the pre-typeID-postfix-approach.
-cp ${CURINSTCONF}/systools.conf.${CURDIST} ${CURINSTCONF}/systools.conf
-###########
+# ###########
+# #REMARK:
+# #  Do this for a short migration time of legacy only, threafter
+# #  use seamlessly the pre-typeID-postfix-approach.
+# cp ${CURINSTCONF}/systools.conf.${CURDIST} ${CURINSTCONF}/systools.conf
+# ###########
 
 
 ######################################################################
@@ -201,7 +284,7 @@ echo "    Check accesibility of ctys scripts by their standard shells."
 echo
 ######################################################################
 STDPATH="/bin/bash"
-CURPATH=`which bash`
+CURPATH=`gwhich bash`
 if [ "${CURPATH}" == "${STDPATH}" ];then
     echo "      CURRENT(#!${CURPATH}) == ORIGINAL(#!${STDPATH})"
     echo 
@@ -272,6 +355,11 @@ echo "###################"
 echo 
 ${CURCALLDIR}/ctys-install1 $*
 
-
-
+echo
+echo "*********************************************************************"
+echo
+echo "Logout now, and login again for init of the required environment."
+echo
+echo "*********************************************************************"
+echo
 
diff --git a/trunk/ctys/plugins/HOSTs/CLI/hook b/trunk/ctys/plugins/HOSTs/CLI/hook
--- a/trunk/ctys/plugins/HOSTs/CLI/hook
+++ b/trunk/ctys/plugins/HOSTs/CLI/hook
@@ -26,22 +26,23 @@ CLI_PREREQ="bash";
 
 
 _myPKGNAME_CLI="${BASH_SOURCE}"
-_myPKGVERS_CLI="01.01.001a02"
+_myPKGVERS_CLI="01.06.001a09"
 hookInfoAdd $_myPKGNAME_CLI $_myPKGVERS_CLI
 _myPKGBASE_CLI="${_myPKGNAME_CLI%/hook}"
-_CLI="${_myPKGBASE_CLI}hook"
 
-CTRL_CLI_DEFAULT="${CTRL_CLI_DEFAULT:-bash -l -i}"
+
+CLI_VERSTRING=${_myPKGVERS_CLI};
+CLI_PREREQ="HOST-CAPABILITY:CLI-${CLI_VERSTRING}-${MYARCH}";
 
 if [ -d "${HOME}/.ctys" -a -d "${HOME}/.ctys/cli" ];then
-    #Source pre-set environment from user
-    if [ -f "${HOME}/.ctys/cli/cli.conf" ];then
-	. "${HOME}/.ctys/cli/cli.conf"
+    if [ -f "${HOME}/.ctys/cli/cli.conf.${MYOS}" ];then
+	. "${HOME}/.ctys/cli/cli.conf.${MYOS}"
     fi
+fi
 
-    #Source pre-set environment from installation 
-    if [ -f "${MYCONFPATH}/conf/cli/cli.conf" ];then
-	. "${MYCONFPATH}/conf/cli/cli.conf"
+if [ -d "${MYCONFPATH}" -a -d "${MYCONFPATH}/cli" ];then
+    if [ -f "${MYCONFPATH}/cli/cli.conf.${MYOS}" ];then
+	. "${MYCONFPATH}/cli/cli.conf.${MYOS}"
     fi
 fi
 
@@ -74,16 +75,16 @@ fi
 #
 #FUNCEND###############################################################
 function serverRequireCLI () {
-    printVerboseDebug ${DBG_LVL_HAYSTACK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
-    local _CS_SPLIT=`echo ${*}|sed -n 's/ConnectionForwarding/ServerOnly/p'`;
-    local _S=`getSessionType ${*}`;_S=${_S:-$CTRL_SESSIONTYPE};
+    printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
+    local _CS_SPLIT=`echo ${*}|sed -n 's/CONNECTIONFORWARDING/SERVERONLY/p'`;
+    local _S=`getSessionType ${*}`;_S=${_S:-$C_SESSIONTYPE};
     local _A=`getActionResulting ${*}`;
     local _ret=1;
     local _res=;
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
 
 
     #if split not supported server only could be used
@@ -95,8 +96,8 @@ function serverRequireCLI () {
  	_res="${*}";_ret=0;
     fi
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
     echo -n "${_res}";
     return ${_ret};  
 }
@@ -131,35 +132,31 @@ function serverRequireCLI () {
 #
 #FUNCEND###############################################################
 function clientRequireCLI () {
-    printVerboseDebug ${DBG_LVL_HAYSTACK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
-    local _CS_SPLIT=`echo ${*}|sed -n 's/ConnectionForwarding/1/p'`;
-    local _S=`getSessionType ${*}`;_S=${_S:-$CTRL_SESSIONTYPE};
+    printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
+    local _CS_SPLIT=`echo ${*}|sed -n 's/CONNECTIONFORWARDING/1/p'`;
+    local _S=`getSessionType ${*}`;_S=${_S:-$C_SESSIONTYPE};
     local _A=`getActionResulting ${*}`;
     local _ret=1;
     local _res=;
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
 
     #if split not supported server only could be used
     if [ -n "${_CS_SPLIT}" ];then
 	ABORT=1;
-	printERR $LINENO $BASH_SOURCE ${ABORT} "The console type CLI doe not support ConnectionForwarding"
+	printERR $LINENO $BASH_SOURCE ${ABORT} "The console type CLI doe not support CONNECTIONFORWARDING"
 	gotoHell ${ABORT}
     else
  	_res=;_ret=1;
     fi
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
     echo -n "${_res}";
     return ${_ret};  
 }
-
-
-
-
 
 
 #FUNCBEG###############################################################
@@ -185,67 +182,71 @@ function clientRequireCLI () {
 #FUNCEND###############################################################
 function setVersionCLI () {
     local _checkonly=;
+    local _ret=0;
     if [ "$1" == "NOEXIT" ];then
 	local _checkonly=1;        
     fi
 
     local _verstrg=;
-    _CALLEXE=`which bash`;
-    if [ -z "${_CALLEXE}" ];then
+    if [ -z "${CLIEXE}" ];then
 	ABORT=2
-	printERR $LINENO $_CLI ${ABORT} "Missing executable for bash"
-	printERR $LINENO $_CLI ${ABORT} "can not find:"
-	printERR $LINENO $_CLI ${ABORT} " -> bash"
-	printERR $LINENO $_CLI ${ABORT} ""
-	printERR $LINENO $_CLI ${ABORT} "Check your PATH"
-	printERR $LINENO $_CLI ${ABORT} " -> PATH=${PATH}"
-	printERR $LINENO $_CLI ${ABORT} ""
-	if [ "${CTRL_SESSIONTYPE}" == "CLI" -a -z "${_checkonly}" ];then
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Missing executable for bash"
+	printERR $LINENO $BASH_SOURCE ${ABORT} "can not find:"
+	printERR $LINENO $BASH_SOURCE ${ABORT} " -> bash"
+	printERR $LINENO $BASH_SOURCE ${ABORT} ""
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Check your PATH"
+	printERR $LINENO $BASH_SOURCE ${ABORT} " -> PATH=${PATH}"
+	printERR $LINENO $BASH_SOURCE ${ABORT} ""
+	if [ "${C_SESSIONTYPE}" == "CLI" -a -z "${_checkonly}" ];then
 	    gotoHell ${ABORT}
 	else
 	    return ${ABORT}
 	fi
     fi
 
-
-
-    #faulty on OpenBSD:${BASH_VERSION}
-    if [ -n "`bash --version 2>&1|egrep '(GNU bash)'`" ];then
-	_verstrg=bash-`bash --version 2>&1|egrep '(GNU bash)'|awk '{printf("%s %s\n",$4,$5);}'`
+    _verstrg=`${CLIEXE} --version 2>&1|awk '/(GNU bash)/{gsub("-.*","",$4);printf("%s\n",$4);}'`;
+    _verstrg="bash-${_verstrg}-${MYARCH}";
+    ${CLIEXE} --version >/dev/null 2>/dev/null 
+    if [ -n "$_verstrg" -a $? -eq 0 ];then
+	printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${CLIEXE} --version)\"` => [ `setSeverityColor INF OK` ]"
+	_ret=0;
     else
-	printWNG $LINENO $_CLI 0  "Unidentified Software Object - CLIx"
-	printWNG $LINENO $_CLI 0  "Scully is on the road..."
+	printWNG 1 $LINENO $BASH_SOURCE 0  "Missing: CLI=${CLIEXE}"
   	_verstrg=GENERIC
+	CLI_PREREQ="${CLI_PREREQ} <disabled:CLI:bash>";
+	printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${CLIEXE} --version)\"` => [ `setSeverityColor ERR NOK` ]"
+	_ret=1;
     fi
 
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_CLI "CLI"
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_CLI "  _verstrg=${_verstrg}"
-
+    printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "CLI"
+    printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "  _verstrg=${_verstrg}"
 
     #currently somewhat restrictive to specific versions.
     case ${_verstrg} in
-	"bash"*)
+	"bash-"[34]*)
 	    CLI_MAGIC=CLIBASH;
-	    CLI_VERSTRING=${_verstrg};
 	    CLI_STATE=ENABLED;
-	    CLI_PREREQ="bash";
+	    CLI_PREREQ="${CLI_PREREQ}%${_verstrg}";
 	    CLISERVER_OPT=;
 	    CLIVIEWER_OPT=;
+	    _ret=0;
 	    ;;
 
 
-         *)
+        *)
 	    CLI_MAGIC=CLIG;
 	    CLISERVER_OPT=;
 	    CLIVIEWER_OPT=;
+	    _ret=1;
 	    ;;
     esac
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLI_MAGIC       = ${CLI_MAGIC}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLI_VERSTRING   = ${CLI_VERSTRING}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLI_STATE       = ${CLI_STATE}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLI_PREREQ      = ${CLI_PREREQ}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLISERVER_OPT   = ${CLISERVER_OPT}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_CLI "CLIVIEWER_OPT   = ${CLIVIEWER_OPT}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLI_MAGIC       = ${CLI_MAGIC}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLI_VERSTRING   = ${CLI_VERSTRING}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLI_STATE       = ${CLI_STATE}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLI_PREREQ      = ${CLI_PREREQ}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLISERVER_OPT   = ${CLISERVER_OPT}"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "CLIVIEWER_OPT   = ${CLIVIEWER_OPT}"
+    return $_ret
 }
 
 
@@ -301,7 +302,7 @@ function noClientServerSplitSupportedMessageCLI () {
 #
 #FUNCEND###############################################################
 function clientServerSplitSupportedCLI () {
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_CLI "$FUNCNAME $1"
+    printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME $1"
     case $1 in
 	CREATE)return 0;;
 #	CONNECT)return 0;;
@@ -333,18 +334,17 @@ function clientServerSplitSupportedCLI () {
 #
 #FUNCEND###############################################################
 function enumerateMySessionsCLI () {
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_CLI "$FUNCNAME:\$@=${@}"
+    printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:\$@=${@}"
 }
 
 
 
 
 #
-#Managed load of sub-packages which are required in almost any case.
+#Managed load of sub-packages gwhich are required in almost any case.
 #On-demand-loads will be performed within requesting action.
 #
 hookPackage "${_myPKGBASE_CLI}/session"
-#hookPackage "${_myPKGBASE_CLI}/enumerate"
 hookPackage "${_myPKGBASE_CLI}/list"
 hookPackage "${_myPKGBASE_CLI}/info"
 
@@ -372,7 +372,7 @@ hookPackage "${_myPKGBASE_CLI}/info"
 #
 #FUNCEND###############################################################
 function handleCLI () {
-  printVerboseDebug ${DBG_LVL_UID} $LINENO $_CLI "${FUNCNAME}:$*"
+  printDBG $S_CLI ${D_BULK} $LINENO $BASH_SOURCE "${FUNCNAME}:$*"
   local OPMODE=$1;shift
   local ACTION=$1;shift
 
@@ -380,16 +380,23 @@ function handleCLI () {
 
       CREATE) 
           hookPackage "${_myPKGBASE_CLI}/create"
-          createConnectCLI ${OPMODE} ${ACTION} 
+	  case ${OPMODE} in
+              PROLOGUE)
+		  ;;
+              EPILOGUE)
+		  ;;
+	      CHECKPARAM|ASSEMBLE|EXECUTE)
+		  createConnectCLI ${OPMODE} ${ACTION} 
+		  ;;
+	  esac
           ;;
 
       *)
           #unknown
           ABORT=1;
-          printERR $LINENO $_CLI ${ABORT} "System Error, unsupported ACTION for CLI:ACTION=${ACTION} OPMODE=${OPMODE}"
+          printERR $LINENO $BASH_SOURCE ${ABORT} "System Error, unsupported ACTION for CLI:ACTION=${ACTION} OPMODE=${OPMODE}"
           ;;
   esac
-
 }
 
 
@@ -417,20 +424,30 @@ function initCLI () {
   local _initConsequences=$1
   local ret=0;
 
-  printVerboseDebug ${DBG_LVL_SUPPORT} $LINENO $_CLI "$FUNCNAME ${_curInit}"
+  local _raise=$((INITSTATE<_curInit));
 
-  case $_curInit in
-      0);;#NOP - Done by shell
-      1)  #add own help to searchlist for options
-	  MYOPTSFILES="${MYOPTSFILES} ${MYPKGPATH}/HOSTs/CLI/help/${MYLANG}/010_cli"
-          setVersionCLI ${_initConsequences}
-          ret=$?
-	  ;;
-      2);;#Curently nothing todo.
-      3);;#Curently nothing todo.
-      4);;#Curently nothing todo.
-      5);;#Curently nothing todo.
-  esac
+  printDBG $S_CLI ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:${INITSTATE} -> ${_curInit} - ${_raise}"
+
+  if [ "$_raise" == "1" ];then
+      #for raise of INITSTATE do not touch the OS's decisions, just expand.
+      case $_curInit in
+	  0);;#NOP - Done by shell
+	  1)  #add own help to searchlist for options
+	      MYOPTSFILES="${MYOPTSFILES} ${MYHELPPATH}/010_cli"
+              setVersionCLI ${_initConsequences}
+              ret=$?
+	      ;;
+	  2);;
+	  3);;
+	  4);;
+	  5);;
+	  6);;
+      esac
+  else
+      case $_curInit in
+	  *);;
+      esac
+  fi
 
   return $ret
 }
diff --git a/trunk/ctys/plugins/HOSTs/VNC/session b/trunk/ctys/plugins/HOSTs/VNC/session
--- a/trunk/ctys/plugins/HOSTs/VNC/session
+++ b/trunk/ctys/plugins/HOSTs/VNC/session
@@ -8,23 +8,18 @@
 #SHORT:        ctys
 #CALLFULLNAME: Commutate To Your Session
 #LICENCE:      GPL3
-#VERSION:      01_02_007a17
+#VERSION:      01_06_001a15
 #
 ########################################################################
 #
-# Copyright (C) 2007 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
+# Copyright (C) 2007,2008 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
 #
 ########################################################################
 
 _myPKGNAME_VNC_SESSION="${BASH_SOURCE}"
-_myPKGVERS_VNC_SESSION="01.02.001b01"
+_myPKGVERS_VNC_SESSION="01.06.001a15"
 hookInfoAdd $_myPKGNAME_VNC_SESSION $_myPKGVERS_VNC_SESSION
 _myPKGBASE_VNC_SESSION="`dirname ${_myPKGNAME_VNC_SESSION}`"
-
-_VNC_SESSION="${_myPKGBASE_VNC_SESSION}session"
-
-
-
 
 
 #FUNCBEG###############################################################
@@ -37,11 +32,11 @@ _VNC_SESSION="${_myPKGBASE_VNC_SESSION}session"
 #DESCRIPTION:
 #
 # GENERIC-IF-DESCRIPTION:
-#  Gives the termination points port number, to which a client could be 
+#  Gives the termination points port number, to gwhich a client could be 
 #  attachhed. This port is forseen to be used in port-forwarding e.g.
 #  by OpenSSH.
 #
-#  The port is the local port number, which in general has to be mapped 
+#  The port is the local port number, gwhich in general has to be mapped 
 #  on remote site, when already in use. Therefore the application has
 #  to provide a port-number-independent client access protocol in order 
 #  to be used by connection forwarding. In any other case display 
@@ -54,7 +49,7 @@ _VNC_SESSION="${_myPKGBASE_VNC_SESSION}session"
 #  While others require for each channel a seperate litenning port.
 #
 #  So it is up to the specific package to support a function returning 
-#  the required port number which could be used to attach an forwarded 
+#  the required port number gwhich could be used to attach an forwarded 
 #  port. 
 #  
 #  The applications client has to support a remapped port number.
@@ -63,11 +58,11 @@ _VNC_SESSION="${_myPKGBASE_VNC_SESSION}session"
 #
 #PARAMETERS:
 #  <label>
-#    The <label> to which the client will be attached.
+#    The <label> to gwhich the client will be attached.
 #
 #GLOBALS:
 #  VBASEPORT
-#    The baseport for calculations of VNC display number, which is 
+#    The baseport for calculations of VNC display number, gwhich is 
 #    5900. This will be used to calculate the client TP.
 #
 #OUTPUT:
@@ -77,31 +72,28 @@ _VNC_SESSION="${_myPKGBASE_VNC_SESSION}session"
 #
 #  VALUES:
 #    <TP-port>
-#      The TP port, to which a client could be attached.
+#      The TP port, to gwhich a client could be attached.
 #
 #FUNCEND###############################################################
 function getClientTPVNC () {
-    local _arg0=${1%%,*}
-    local _arg1=${1##*,}
+    local _arg0=${1}
 
-    if [ -z "${_arg1}" ];then
- 	local _port=`fetchID4Label ${_arg0}`;
-	if [ -z "${_port}" ];then
-            _port=`fetchLabel4ID ${_arg0}`;
-	fi
-	if [ -z "${_port}" ];then
-	    ABORT=2
-	    printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:Error, can not get port number for label:${1}"
-	    gotoHell ${ABORT}
-	fi
-    else
-	_port=${_arg1};
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME Label=$_arg0"
+
+    local _port=`fetchID4Label ${_arg0}`;
+    if [ -z "${_port}" ];then
+        _port=`fetchLabel4ID ${_arg0}`;
+    fi
+    if [ -z "${_port}" ];then
+	ABORT=2
+	printINFO 2 $LINENO $BASH_SOURCE 0 "${FUNCNAME}:Cannot get port number for label:${1}"
+	gotoHell ${ABORT}
     fi
 
     local _ret=;
     let _ret=VNC_BASEPORT+_port;
     
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "$FUNCNAME port number=$_ret from ID=$_port"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME port number=$_ret from ID=$_port"
     echo ${_ret}
 }
 
@@ -118,6 +110,7 @@ function getClientTPVNC () {
 #EXAMPLE:
 #
 #PARAMETERS:
+#  $1: label
 #
 #OUTPUT:
 #  RETURN:
@@ -126,80 +119,106 @@ function getClientTPVNC () {
 #
 #FUNCEND###############################################################
 function startSessionVNC () {
-  printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "$FUNCNAME"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME"
     local _name=${1:-DEFAULT-`date +%y%m%d%H%M%S`}
-    printVerboseDebug ${DBG_LVL_UI} $LINENO $_VNC_SESSION "${VNCSERVER} <session-label>:${_name}"
+    printDBG $S_VNC ${D_UI} $LINENO $BASH_SOURCE "${VNCSERVER} <session-label>:${_name}"
     checkUniqueness4Label ${_name};
     if [ $? -eq 0 ];then
 	local _unique=1
     else
-	if [ -z "${CTRL_ALLOWAMBIGIOUS}" ];then
+	if [ -z "${C_ALLOWAMBIGIOUS}" ];then
 	    ABORT=2
-	    printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:Ambigious <session-label>:${_name}"
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:Ambigious <session-label>:${_name}"
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:VNC is as default in \"shared\" mode, use \"-A\" if required."
 	    gotoHell ${ABORT}
 	else 
-	    printWNG $LINENO $_VNC_SESSION ${RET} "${FUNCNAME}:Label is ambigious:${_name}"
+	    printWNG 1 $LINENO $BASH_SOURCE ${RET} "${FUNCNAME}:Reuse ambigious label:${_name}"
 	fi
     fi
 
     #prepare server-opts, particulary servers display resolution.
     local CURSES=""
     local _serveropt="-name ${_name} ${VNCSERVER_OPT}"
-    if [ -n "${CTRL_REMOTERESOLUTION}" ];then
+    if [ -n "${C_REMOTERESOLUTION}" ];then
         #use explicityl given
-	printVerboseDebug ${DBG_LVL_UID} $LINENO $_VNC_SESSION "CTRL_REMOTERESOLUTION=${CTRL_REMOTERESOLUTION}"
-	local _servergeo=${CTRL_REMOTERESOLUTION}
+	printDBG $S_VNC ${D_UID} $LINENO $BASH_SOURCE "C_REMOTERESOLUTION=${C_REMOTERESOLUTION}"
+	local _servergeo=${C_REMOTERESOLUTION}
 	_serveropt=`echo ${_serveropt}|sed 's/-geometry [0-9]*x[0-9x]*//g'`
-	printVerboseDebug ${DBG_LVL_UID} $LINENO $_VNC_SESSION "_servergeo=${_servergeo}"
+	printDBG $S_VNC ${D_UID} $LINENO $BASH_SOURCE "_servergeo=${_servergeo}"
 
     else
-	if [ -n "${CTRL_GEOMETRY}" ];then
+	if [ -n "${C_GEOMETRY}" ];then
             #use same as given for client
-	    printVerboseDebug ${DBG_LVL_UID} $LINENO $_VNC_SESSION "CTRL_GEOMETRY=${CTRL_GEOMETRY}"
-	    local _servergeo=`echo ${CTRL_GEOMETRY}|sed -n 's/[^0-9]*\([0-9x]*\).*$/\1/gp'`
+	    printDBG $S_VNC ${D_UID} $LINENO $BASH_SOURCE "C_GEOMETRY=${C_GEOMETRY}"
+	    local _servergeo=`echo ${C_GEOMETRY}|sed -n 's/+.*$//;s/[^0-9]*\([0-9x]*\).*$/\1/gp'`
 	    _serveropt=`echo ${_serveropt}|sed 's/-geometry [0-9]*x[0-9x]*//g'`
-	    printVerboseDebug ${DBG_LVL_UID} $LINENO $_VNC_SESSION "_servergeo=${_servergeo}"
+	    printDBG $S_VNC ${D_UID} $LINENO $BASH_SOURCE "_servergeo=${_servergeo}"
 	fi
     fi
     _serveropt="${_serveropt}  ${_servergeo:+ -geometry $_servergeo} "
 
-    local _vieweropt="${VNCVIEWER_OPT} ${CTRL_GEOMETRY:+ -geometry $CTRL_GEOMETRY} "
+    local _vieweropt="${VNCVIEWER_OPT} ${C_GEOMETRY:+ -geometry $C_GEOMETRY} "
 
-    if [ -z "${CTRL_NOEXEC}" ];then
-	if [ "${CTRL_CLIENTLOCATION}" !=  "-L ConnectionForwarding" ];then
-	    SERVER="${VNCSERVER} ${CTRL_VERBOSE:+ -d $CTRL_VERBOSE} ${_serveropt}"
-	    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "SERVER=${SERVER}"
+    if [ -z "${C_NOEXEC}" ];then
+	if [ "${C_CLIENTLOCATION}" !=  "-L CONNECTIONFORWARDING" ];then
+	    SERVER="${VNCSERVER} ${C_DARGS} ${_serveropt}"
+	    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "SERVER=${SERVER}"
+
 	    CURSES=`eval ${SERVER}`
-	    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "CURSES=${CURSES}"
+	    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "CURSES=${CURSES}"
 	    if [ -z "${CURSES}" -o -n "`echo ${CURSES}|sed 's/[0-9]*//g'`" ];then
 		ABORT=2
-		printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:Error when starting VNCSERVER:"
-		printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:  ${VNCSERVER} ${_serveropt}"
-		printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:  => CURSES=${CURSES}"
-		printERR $LINENO $_VNC_SESSION ${ABORT} "."
-		printERR $LINENO $_VNC_SESSION ${ABORT} "A common reason for this is an error for platform depency of passwd file."
-		printERR $LINENO $_VNC_SESSION ${ABORT} "Call \"vncpasswd\" on the target machine and try creation of the session again."
-		printERR $LINENO $_VNC_SESSION ${ABORT} "."
+		printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:Error when starting VNCSERVER:"
+		printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:  ${VNCSERVER} ${_serveropt}"
+		printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:  => CURSES=${CURSES}"
+		printERR $LINENO $BASH_SOURCE ${ABORT} "."
+		printERR $LINENO $BASH_SOURCE ${ABORT} "A common reason for this is an error for platform depency "
+		printERR $LINENO $BASH_SOURCE ${ABORT} "of default passwd file."
+		printERR $LINENO $BASH_SOURCE ${ABORT} "Call \"vncpasswd\" on the target machine and try creation "
+		printERR $LINENO $BASH_SOURCE ${ABORT} "of the session again."
+		printERR $LINENO $BASH_SOURCE ${ABORT} "This should already have be done anyhow."
+		printERR $LINENO $BASH_SOURCE ${ABORT} "."
 		gotoHell ${ABORT}
 	    else
-		printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "VNC:Current vncserver Xsession detected as successfull CURSES=<${CURSES}>"
+		printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "VNC:Current vncserver Xsession detected as successfull CURSES=<${CURSES}>"
 	    fi   
+
+	    cacheStoreWorkerPIDData SERVER VNC "${CURSES}" "${_name}" 0 "" 
+	    if [ $? -ne 0 ];then
+		printERR $LINENO $BASH_SOURCE 2 "$FUNCNAME:VNC:Failed to store runtime JobData for SERVER:\"${_name}\""
+		printERR $LINENO $BASH_SOURCE 2 "$FUNCNAME:VNC: =>Continue for now, but further actions may be required!"
+	    fi
 	fi
     else
         #Dummy-value for display only
 	CURSES=9999999
     fi
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "CURSES=$CURSES"
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "CTRL_CLIENTLOCATION=<$CTRL_CLIENTLOCATION>"
-    if [ "${CTRL_CLIENTLOCATION}" !=  "-L ServerOnly" ];then
-	local CALLER="export CTRL_ASYNC;${VNCVIEWER}  "
-	local CALLER="${CALLER} ${CTRL_VERBOSE:+ -d $CTRL_VERBOSE} -name \"${_name}:${CURSES}\" "
-	local CALLER="${CALLER} ${_vieweropt} localhost:${CURSES} "
-	printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "${CTRL_NOEXEC:-CALL:}${CALLER}"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "CURSES=$CURSES"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "C_CLIENTLOCATION=<$C_CLIENTLOCATION>"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "CALLERJOB=<$CALLERJOB>"
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "JOB_IDXSUB=<$JOB_IDXSUB>"
+    if [ "${C_CLIENTLOCATION}" !=  "-L SERVERONLY" ];then
+	local CALLER=;
+	CALLER="export C_ASYNC=${C_ASYNC}&&${VNCVIEWER}  "
+	CALLER="${CALLER} ${C_DARGS} "
+	CALLER="${CALLER} -name \"${_name}:${CURSES}\" "
+	CALLER="${CALLER} ${_vieweropt} localhost:${CURSES} "
+	printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "${C_NOEXEC:-CALL:}${CALLER}"
         #don't exec here, it could be one of a set!
-	printVerboseDebug ${DBG_LVL_UID} $LINENO $_VNC_SESSION "VNCVIEWER_DELAY=${VNCVIEWER_DELAY}"
-	sleep ${VNCVIEWER_DELAY:-2}
-	[ -z "${CTRL_NOEXEC}" ]&&eval ${CALLER}
+	printDBG $S_VNC ${D_UID} $LINENO $BASH_SOURCE "WAITS=${WAITS}"
+	sleep ${WAITS:-2}
+	if [ -z "${C_NOEXEC}" ];then
+	    eval ${CALLER} &
+	    sleep ${WAITS:-1}
+ 	    cacheStoreWorkerPIDData CLIENT VNC "${CURSES}" "${_name}" 0 "" 
+	    if [ $? -ne 0 ];then
+		printWNG 1 $LINENO $BASH_SOURCE 0  "$FUNCNAME:VNC:Failed to store runtime JobData for CLIENT:\"${_name}\""
+		printWNG 1 $LINENO $BASH_SOURCE 0  "$FUNCNAME:VNC: =>Restart of CLIENT should be sufficient."
+	    fi
+	    if [ "${C_ASYNC}" == 0 ];then
+		wait
+	    fi
+	fi
     fi
 }
 
@@ -231,50 +250,50 @@ function startSessionVNC () {
 #
 #FUNCEND###############################################################
 function connectSessionVNC () {
-  local _id0=${1}
-  local _id=`removeLeadZeros ${1}`
-  local _label=${2}
-  printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_VNC_SESSION "$FUNCNAME ${_id0}->${_id} ${_label}"
+    local _id0=${1}
+    local _id=`removeLeadZeros ${1}`
+    local _label=${2}
+    printDBG $S_VNC ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME ${_id0}->${_id} ${_label}"
 
-  if [ -z "${_label}" -a -z "${_id}" ];then
-    ABORT=1
-    printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:At least one parameter required:<session-id> or <session-label>"
-    gotoHell ${ABORT}
-  fi
-
-  #not-having could be tolerated, even though something might be basically wrong.
-  if [ -z "${_label}" -a -n "${_id}"   ]; then 
-    _label=`fetchLabel4ID ${_id}`;
-    if [ -z "${_label}" ];then
-      _label=DEFAULT;
+    if [ -z "${_label}" -a -z "${_id}" ];then
+	ABORT=1
+	printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:At least one parameter required:<session-id> or <session-label>"
+	gotoHell ${ABORT}
     fi
-  fi
 
-  #missing could definitely NOT be tolerated, so abort if fails.
-  if [ -n "${_label}" -a -z "${_id}" ]; then 
-    _id=`fetchID4Label ${_label}`;
-    if [ -z "${_id}" ];then
-      ABORT=1
-      printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:Fetch of <session-id> failed:_label=${_label}"
-      gotoHell ${ABORT}
+    #not-having could be tolerated, even though something might be basically wrong.
+    if [ -z "${_label}" -a -n "${_id}"   ]; then 
+	_label=`fetchLabel4ID ${_id}`;
+	if [ -z "${_label}" ];then
+	    _label=DEFAULT;
+	fi
     fi
-  fi
 
-  #even though this condition might be impossible now, let it beeeee ...
-  if [ -z "${_label}" -a -z "${_id}" ];then
-    ABORT=1
-    printERR $LINENO $_VNC_SESSION ${ABORT} "${FUNCNAME}:Fetch of peer entry failed:_id=${_id} - _label=${_label}"
-    gotoHell ${ABORT}
-  fi
+    #missing could definitely NOT be tolerated, so abort if fails.
+    if [ -n "${_label}" -a -z "${_id}" ]; then 
+	_id=`fetchID4Label ${_label}`;
+	if [ -z "${_id}" ];then
+	    ABORT=1
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:Fetch of <session-id> failed:_label=${_label}"
+	    gotoHell ${ABORT}
+	fi
+    fi
 
-  printVerboseDebug ${DBG_LVL_OVERKILL} $LINENO $_VNC_SESSION "OK:_id=${_id} - _label=${_label}"
-  #
-  #Now shows name+id in title, id could not be set for server as default.
-  local _vieweropt="-name ${_label}:${_id} ${VNCVIEWER_OPT} ${CTRL_GEOMETRY:+ -geometry $CTRL_GEOMETRY} "
-  local CALLER="${VNCVIEWER} ${CTRL_VERBOSE:+ -d $CTRL_VERBOSE} ${_vieweropt} localhost:${_id}"
-  printVerboseDebug ${DBG_LVL_OVERKILL} $LINENO $_VNC_SESSION "${CALLER}"
-  export CTRL_ASYNC;
-  [ -z "${CTRL_NOEXEC}" ]&&eval ${CALLER}
+    #even though this condition might be impossible now, let it beeeee ...
+    if [ -z "${_label}" -a -z "${_id}" ];then
+	ABORT=1
+	printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:Fetch of peer entry failed:_id=${_id} - _label=${_label}"
+	gotoHell ${ABORT}
+    fi
+
+    printDBG $S_VNC ${D_FRAME} $LINENO $BASH_SOURCE "OK:_id=${_id} - _label=${_label}"
+    #
+    #Now shows name+id in title, id could not be set for server as default.
+    local _vieweropt="-name ${_label}:${_id} ${VNCVIEWER_OPT} ${C_GEOMETRY:+ -geometry $C_GEOMETRY} "
+    local CALLER="${VNCVIEWER} ${C_DARGS} ${_vieweropt} localhost:${_id}"
+    printDBG $S_VNC ${D_FRAME} $LINENO $BASH_SOURCE "${CALLER}"
+    export C_ASYNC;
+    [ -z "${C_NOEXEC}" ]&&eval ${CALLER}
 }
 
 
