01_07_001a01:commit

diff --git a/ctys/bin/ctys-callVncviewer b/ctys/bin/ctys-callVncviewer
--- a/ctys/bin/ctys-callVncviewer
+++ b/ctys/bin/ctys-callVncviewer
@@ -1,4 +1,33 @@
 #!/bin/bash
+########################################################################
+#
+#PROJECT:      Unified Sessions Manager
+#AUTHOR:       Arno-Can Uestuensoez - acue@UnifiedSessionsManager.org
+#MAINTAINER:   Arno-Can Uestuensoez - acue_sf1@sourceforge.net
+#SHORT:        ctys
+#CALLFULLNAME: Commutate To Your Session
+#LICENCE:      GPL3
+#VERSION:      01_05_001a01
+#
+########################################################################
+#
+#     Copyright (C) 2007 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
+#
+#     This program is free software: you can redistribute it and/or modify
+#     it under the terms of the GNU General Public License as published by
+#     the Free Software Foundation, either version 3 of the License, or
+#     (at your option) any later version.
+#
+#     This program is distributed in the hope that it will be useful,
+#     but WITHOUT ANY WARRANTY; without even the implied warranty of
+#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#     GNU General Public License for more details.
+#
+#     You should have received a copy of the GNU General Public License
+#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+########################################################################
+
 
 ################################################################
 #                   Begin of FrameWork                         #
@@ -55,7 +84,6 @@ shopt -s nullglob
 #       System definitions - do not change these!              #
 ################################################################
 #Execution anchor
-MYHOST=`uname -n`
 MYCALLPATHNAME=$0
 MYCALLNAME=`basename $MYCALLPATHNAME`
 
@@ -85,7 +113,7 @@ EOF
   exit 1
 fi
 
-MYBOOTSTRAP=${MYBOOTSTRAP}/bootstrap.01.01.001
+MYBOOTSTRAP=${MYBOOTSTRAP}/bootstrap.01.01.002
 if [ ! -f "${MYBOOTSTRAP}" ];then
   echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYBOOTSTRAP=${MYBOOTSTRAP}"
 cat <<EOF  
@@ -126,7 +154,7 @@ fi
 . ${MYBOOTSTRAP}
 ###################################################
 #OK - utilities to find components of this version#
-#available now.                                   #
+#are available now.                               #
 ###################################################
 
 #
@@ -152,17 +180,14 @@ bootstrapCheckInitialPath
 ###################################################
 #OK - Now should work.                            #
 ###################################################
-
-MYHELPPATH=${MYLIBPATH}/help/${MYLANG}
-if [ ! -d "${MYHELPPATH}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYHELPPATH=${MYHELPPATH}"
-  exit 1
-fi
-
 MYCONFPATH=${MYLIBPATH}/conf/ctys
 if [ ! -d "${MYCONFPATH}" ];then
   echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYCONFPATH=${MYCONFPATH}"
   exit 1
+fi
+
+if [ -f "${MYCONFPATH}/versinfo.conf" ];then
+    . ${MYCONFPATH}/versinfo.conf
 fi
 
 MYMACROPATH=${MYCONFPATH}/macros
@@ -183,10 +208,21 @@ MYINSTALLPATH= #Value is assigned in base. Symbolic links are replaced by target
 ##############################################
 #load basic library required for bootstrap   #
 ##############################################
+if [ ! -f "${MYLIBPATH}/lib/base" ];then
+  echo "${MYCALLNAME}:$LINENO:ERROR:Missing mandatory initial library:${MYLIBPATH}/lib/base"
+  exit 1
+fi
 . ${MYLIBPATH}/lib/base
+
+
+if [ ! -f "${MYLIBPATH}/lib/libManager" ];then
+  echo "${MYCALLNAME}:$LINENO:ERROR:Missing mandatory initial library:${MYLIBPATH}/lib/libManager"
+  exit 1
+fi
 . ${MYLIBPATH}/lib/libManager
+
 #
-#Germish: "Was the egg or the chicken first?"
+#"Was the egg or the chicken first?"
 #
 #..and prevent real load order for later display.
 #
@@ -197,13 +233,14 @@ libManagerRegisterLib
 #Now the environment is armed, so let's go.  #
 ##############################################
 
+
 if [ ! -d "${MYINSTALLPATH}" ];then
     ABORT=1;
     printERR $LINENO $BASH_SOURCE ${ABORT} "Missing:MYINSTALLPATH=${MYINSTALLPATH}"
     gotoHell ${ABORT}
 fi
 
-MYOPTSFILES=${MYOPTSFILES:-$MYLIBPATH/help/$MYLANG/085_base_options} 
+MYOPTSFILES=${MYOPTSFILES:-$MYLIBPATH/help/$MYLANG/*_base_options} 
 checkFileListElements "${MYOPTSFILES}"
 if [ $? -ne 0 ];then
     ABORT=1;
@@ -234,9 +271,25 @@ TARGET_WM_SOON="fvwm"
 #to be tested - coming soon
 TARGET_WM_FORESEEN="KDE(might work now)"
 
+
+
 ################################################################
 #                     End of FrameWork                         #
 ################################################################
+
+#
+#Verify OS support
+#
+case ${MYOS} in
+    Linux);;
+    OpenBSD);;
+    SunOS);;
+    *)
+        printINFO 1 $LINENO $BASH_SOURCE 1 "${MYCALLNAME} is not supported on ${MYOS}"
+	gotoHell 0
+	;;
+esac
+
 
 . ${MYLIBPATH}/lib/cli/cli
 
@@ -246,32 +299,37 @@ if [ -f "${HOME}/.ctys/ctys.conf" ];then
 fi
 
 #Source pre-set environment from installation 
-if [ -f "${MYCONFPATH}/conf/ctys.conf" ];then
-  . "${MYCONFPATH}/conf/ctys.conf"
-fi
-
-#Source pre-set environment from installation 
-if [ -f "${MYCONFPATH}/conf/vnc/vnc.conf" ];then
-  . "${MYCONFPATH}/conf/vnc/vnc.conf"
+if [ -f "${MYCONFPATH}/ctys.conf" ];then
+  . "${MYCONFPATH}/ctys.conf"
 fi
 
 #system tools
-if [ -f "${HOME}/.ctys/systools.conf" ];then
-    . "${HOME}/.ctys/systools.conf"
-else
+if [ -f "${HOME}/.ctys/systools.conf.${MYDIST}" ];then
+    . "${HOME}/.ctys/systools.conf.${MYDIST}"
+fi
 
-    if [ -f "${MYCONFPATH}/conf/ctys/systools.conf" ];then
-	. "${MYCONFPATH}/conf/ctys/systools.conf"
+if [ -f "${MYCONFPATH}/systools.conf.${MYDIST}" ];then
+    . "${MYCONFPATH}/systools.conf.${MYDIST}"
+else
+    if [ -f "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}" ];then
+	. "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}"
     else
-	if [ -f "${MYCALLPATH}/../conf/ctys/systools.conf" ];then
-	    . "${MYCALLPATH}/../conf/ctys/systools.conf"
-	else
-	    ABORT=1;
-	    printERR $LINENO $BASH_SOURCE ${ABORT} "Missing system tools configuration file:\"systools.conf\""
-	    printERR $LINENO $BASH_SOURCE ${ABORT} "Check your installation."
-	    gotoHell ${ABORT}
-	fi
+	ABORT=1;
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Missing system tools configuration file:\"systools.conf.${MYDIST}\""
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Check your installation."
+	gotoHell ${ABORT}
     fi
+fi
+
+
+#Source pre-set environment from user
+if [ -f "${HOME}/.ctys/vnc/vnc.conf.${MYOS}" ];then
+  . "${HOME}/.ctys/vnc/vnc.conf.${MYOS}"
+fi
+
+#Source pre-set environment from user
+if [ -f "${MYCONFPATH}/vnc/vnc.conf.${MYOS}" ];then
+  . "${MYCONFPATH}/vnc/vnc.conf.${MYOS}"
 fi
 
 ################################################################
@@ -279,10 +337,10 @@ fi
 ################################################################
 
 if [ "${*}" != "${*//-X/}" ];then
-    CTRL_TERSE=1
+    C_TERSE=1
 fi
 if [ "${*}" != "${*//-V/}" ];then
-    if [ -n "${CTRL_TERSE}" ];then
+    if [ -n "${C_TERSE}" ];then
 	echo -n ${VERSION}
     else
 	echo "$0: VERSION=${VERSION}"
@@ -291,37 +349,29 @@ if [ "${*}" != "${*//-V/}" ];then
 fi
 
 
-
 #Used only for current script, to be removed for vncviewer
-CLILIBONLY="-d "
+CLILIBONLY="-d -j "
 
 #Defaults fo vncviewer.
 CLIDEFAULTS="-passwd ~/.vnc/passwd "
 
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "DISPLAY=$DISPLAY"
 
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "\$@=$@"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "\$@=$@"
 X="`cliOptionsStrip REMOVE $CLILIBONLY -- $@`"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "\$X=$X"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "\$X=$X"
 X="`cliOptionsAddMissing $CLIDEFAULTS -- $X`"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "\$X=$X"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "\$X=$X"
 
 
 OUTPUT="${VNCVIEWER_NATIVE} ${X}"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "PATH=${PATH}"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "PWD=${PWD}"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "CALL=${OUTPUT}"
-printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "CTRL_ASYNC=${CTRL_ASYNC}"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "PATH=${PATH}"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "PWD=${PWD}"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "CALL=${OUTPUT}"
+printDBG $S_BIN ${D_MAINT} $LINENO $BASH_SOURCE "C_ASYNC=${C_ASYNC}"
 
-
-if [ "${CTRL_ASYNC}" == 1 ];then
-    eval ${OUTPUT} &
+if [ "${C_ASYNC}" == 0 ];then
+    eval ${OUTPUT}  
 else
-    eval ${OUTPUT}
+    exec ${BASHEXE} -c "${OUTPUT} " &
 fi
-
-# OUTPUT=`${OUTPUT} 2>&1 &`
-# RESULT=${OUTPUT}
-# printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "RESULT=${RESULT}"
-# echo $RESULT >&2
-
-
diff --git a/ctys/bin/ctys-vping b/ctys/bin/ctys-vping
--- a/ctys/bin/ctys-vping
+++ b/ctys/bin/ctys-vping
@@ -1,5 +1,35 @@
 #!/bin/bash
 
+########################################################################
+#
+#PROJECT:      Unified Sessions Manager
+#AUTHOR:       Arno-Can Uestuensoez - acue@UnifiedSessionsManager.org
+#MAINTAINER:   Arno-Can Uestuensoez - acue_sf1@sourceforge.net
+#SHORT:        ctys
+#CALLFULLNAME: Commutate To Your Session
+#LICENCE:      GPL3
+#VERSION:      01_06_001a15
+#
+########################################################################
+#
+#     Copyright (C) 2007,2008 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
+#
+#     This program is free software: you can redistribute it and/or modify
+#     it under the terms of the GNU General Public License as published by
+#     the Free Software Foundation, either version 3 of the License, or
+#     (at your option) any later version.
+#
+#     This program is distributed in the hope that it will be useful,
+#     but WITHOUT ANY WARRANTY; without even the implied warranty of
+#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#     GNU General Public License for more details.
+#
+#     You should have received a copy of the GNU General Public License
+#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+########################################################################
+
+
 ################################################################
 #                   Begin of FrameWork                         #
 ################################################################
@@ -29,7 +59,7 @@ LICENCE=GPL3
 #  bash-script
 #
 #VERSION:
-VERSION=01_01_001a01
+VERSION=01_06_001a15
 #DESCRIPTION:
 #  Ping by cts-address.
 #
@@ -92,53 +122,53 @@ MYCALLPATH=`dirname $MYCALLPATHNAME`
 ###################################################
 MYBOOTSTRAP=${MYCALLPATH}/bootstrap
 if [ ! -d "${MYBOOTSTRAP}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYBOOTSTRAP=${MYBOOTSTRAP}"
-cat <<EOF  
+    echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYBOOTSTRAP=${MYBOOTSTRAP}"
+    cat <<EOF  
 
 DESCRIPTION:
-  This directory contains the common mandatory bootstrap functions.
-  Your installation my be erroneous.  
+This directory contains the common mandatory bootstrap functions.
+Your installation my be erroneous.  
 
 SOLUTION-PROPOSAL:
-  First of all check your installation, because an error at this level
-  might - for no reason - bypass the final tests.
+First of all check your installation, because an error at this level
+might - for no reason - bypass the final tests.
 
-  If this does not help please send a bug-report.
+If this does not help please send a bug-report.
 
 EOF
   exit 1
 fi
 
-MYBOOTSTRAP=${MYBOOTSTRAP}/bootstrap.01.01.001
+MYBOOTSTRAP=${MYBOOTSTRAP}/bootstrap.01.01.002
 if [ ! -f "${MYBOOTSTRAP}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYBOOTSTRAP=${MYBOOTSTRAP}"
-cat <<EOF  
+    echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYBOOTSTRAP=${MYBOOTSTRAP}"
+    cat <<EOF  
 
 DESCRIPTION:
-  This file contains the common mandatory bootstrap functions required
-  for start-up of any shell-script within this package.
+This file contains the common mandatory bootstrap functions required
+for start-up of any shell-script within this package.
 
-  It seems though your installation is erroneous or you detected a bug.  
+It seems though your installation is erroneous or you detected a bug.  
 
 SOLUTION-PROPOSAL:
-  First of all check your installation, because an error at this level
-  might - for no reason - bypass the final tests.
+First of all check your installation, because an error at this level
+might - for no reason - bypass the final tests.
 
-  When your installation seems to be OK, you may try to set a TEMPORARY
-  symbolic link to one of the files named as "bootstrap.<highest-version>".
-  
-    ln -s ${MYBOOTSTRAP} bootstrap.<highest-version>
+When your installation seems to be OK, you may try to set a TEMPORARY
+symbolic link to one of the files named as "bootstrap.<highest-version>".
 
-  in order to continue for now. 
+ln -s ${MYBOOTSTRAP} bootstrap.<highest-version>
 
-  Be aware, that any installation containing the required file will replace
-  the symbolic link, because as convention the common boostrap files are
-  never symbolic links, thus only recognized as a temporary workaround to 
-  be corrected soon.
+in order to continue for now. 
 
-  If this does not work you could try one of the other versions.
+Be aware, that any installation containing the required file will replace
+the symbolic link, because as convention the common boostrap files are
+never symbolic links, thus only recognized as a temporary workaround to 
+be corrected soon.
 
-  Please send a bug-report.
+If this does not work you could try one of the other versions.
+
+Please send a bug-report.
 
 EOF
   exit 1
@@ -182,20 +212,24 @@ bootstrapCheckInitialPath
 
 MYCONFPATH=${MYLIBPATH}/conf/ctys
 if [ ! -d "${MYCONFPATH}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYCONFPATH=${MYCONFPATH}"
-  exit 1
+    echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYCONFPATH=${MYCONFPATH}"
+    exit 1
+fi
+
+if [ -f "${MYCONFPATH}/versinfo.conf" ];then
+    . ${MYCONFPATH}/versinfo.conf
 fi
 
 MYMACROPATH=${MYCONFPATH}/macros
 if [ ! -d "${MYMACROPATH}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYMACROPATH=${MYMACROPATH}"
-  exit 1
+    echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYMACROPATH=${MYMACROPATH}"
+    exit 1
 fi
 
 MYPKGPATH=${MYLIBPATH}/plugins
 if [ ! -d "${MYPKGPATH}" ];then
-  echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYPKGPATH=${MYPKGPATH}"
-  exit 1
+    echo "${MYCALLNAME}:$LINENO:ERROR:Missing:MYPKGPATH=${MYPKGPATH}"
+    exit 1
 fi
 
 MYINSTALLPATH= #Value is assigned in base. Symbolic links are replaced by target
@@ -224,7 +258,7 @@ if [ ! -d "${MYINSTALLPATH}" ];then
     gotoHell ${ABORT}
 fi
 
-MYOPTSFILES=${MYOPTSFILES:-$MYLIBPATH/help/$MYLANG/085_base_options} 
+MYOPTSFILES=${MYOPTSFILES:-$MYLIBPATH/help/$MYLANG/*_base_options} 
 checkFileListElements "${MYOPTSFILES}"
 if [ $? -ne 0 ];then
     ABORT=1;
@@ -259,7 +293,52 @@ TARGET_WM_FORESEEN="KDE(might work now)"
 #                     End of FrameWork                         #
 ################################################################
 
+
+#
+#Verify OS support
+#
+case ${MYOS} in
+    Linux);;
+    OpenBSD);;
+    SunOS);;
+    *)
+        printINFO 1 $LINENO $BASH_SOURCE 1 "${MYCALLNAME} is not supported on ${MYOS}"
+	gotoHell 0
+	;;
+esac
+
+
+#Source pre-set environment from user
+if [ -f "${HOME}/.ctys/ctys.conf" ];then
+    . "${HOME}/.ctys/ctys.conf"
+fi
+
+#Source pre-set environment from installation 
+if [ -f "${MYCONFPATH}/ctys.conf" ];then
+    . "${MYCONFPATH}/ctys.conf"
+fi
+
+#system tools
+if [ -f "${HOME}/.ctys/systools.conf.${MYDIST}" ];then
+    . "${HOME}/.ctys/systools.conf.${MYDIST}"
+else
+
+    if [ -f "${MYCONFPATH}/systools.conf.${MYDIST}" ];then
+	. "${MYCONFPATH}/systools.conf.${MYDIST}"
+    else
+	if [ -f "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}" ];then
+	    . "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}"
+	else
+	    ABORT=1;
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "Missing system tools configuration file:\"systools.conf.${MYDIST}\""
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "Check your installation."
+	    gotoHell ${ABORT}
+	fi
+    fi
+fi
+
 #assure for append...
+printDBG $S_BIN ${D_FLOW} $LINENO $BASH_SOURCE "CTYS_GROUPS_PATH=\"${CTYS_GROUPS_PATH}\""
 if [ -n "$CTYS_GROUPS_PATH" ];then
     mstr=$HOME/.ctys/groups
     CTYS_GROUPS_PATH=${CTYS_GROUPS_PATH//$mstr}
@@ -286,9 +365,11 @@ if [ ! -d "${MYCONFPATH}/groups" ];then
 fi
 
 CTYS_GROUPS_PATH="${HOME}/.ctys/groups:${MYCONFPATH}/groups${CTYS_GROUPS_PATH:+:$CTYS_GROUPS_PATH}"
+printDBG $S_BIN ${D_FLOW} $LINENO $BASH_SOURCE "CTYS_GROUPS_PATH=\"${CTYS_GROUPS_PATH}\""
 
 
 
+. ${MYLIBPATH}/lib/misc
 . ${MYLIBPATH}/lib/help/help
 . ${MYLIBPATH}/lib/groups
 
@@ -299,35 +380,35 @@ if [ -d "${HOME}/.ctys/db/default" ];then
 fi
 
 #path to directory containing the default mapping db
-if [ -d "${MYCONFPATH}/conf/db/default" ];then
+if [ -d "${MYCONFPATH}/db/default" ];then
     DEFAULT_DBPATHLST=${DEFAULT_DBPATHLST:-$HOME/conf/db/default}
 fi
 
 
 #Source pre-set environment from user
 if [ -f "${HOME}/.ctys/ctys.conf" ];then
-  . "${HOME}/.ctys/ctys.conf"
+    . "${HOME}/.ctys/ctys.conf"
 fi
 
 #Source pre-set environment from installation 
-if [ -f "${MYCONFPATH}/conf/ctys.conf" ];then
-  . "${MYCONFPATH}/conf/ctys.conf"
+if [ -f "${MYCONFPATH}/ctys.conf" ];then
+    . "${MYCONFPATH}/ctys.conf"
 fi
 
 
 #system tools
-if [ -f "${HOME}/.ctys/systools.conf" ];then
-    . "${HOME}/.ctys/systools.conf"
+if [ -f "${HOME}/.ctys/systools.conf.${MYDIST}" ];then
+    . "${HOME}/.ctys/systools.conf.${MYDIST}"
 else
 
-    if [ -f "${MYCONFPATH}/conf/ctys/systools.conf" ];then
-	. "${MYCONFPATH}/conf/ctys/systools.conf"
+    if [ -f "${MYCONFPATH}/systools.conf.${MYDIST}" ];then
+	. "${MYCONFPATH}/systools.conf.${MYDIST}"
     else
-	if [ -f "${MYCALLPATH}/../conf/ctys/systools.conf" ];then
-	    . "${MYCALLPATH}/../conf/ctys/systools.conf"
+	if [ -f "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}" ];then
+	    . "${MYCALLPATH}/../conf/ctys/systools.conf.${MYDIST}"
 	else
 	    ABORT=1;
-	    printERR $LINENO $BASH_SOURCE ${ABORT} "Missing system tools configuration file:\"systools.conf\""
+	    printERR $LINENO $BASH_SOURCE ${ABORT} "Missing system tools configuration file:\"systools.conf.${MYDIST}\""
 	    printERR $LINENO $BASH_SOURCE ${ABORT} "Check your installation."
 	    gotoHell ${ABORT}
 	fi
@@ -339,19 +420,41 @@ fi
 #    Default definitions - User-Customizable  from shell       #
 ################################################################
 
+case "${MYOS}" in
+    Linux)
+	CTYS_PING=`getPathName  $LINENO $BASH_SOURCE ERROR ping  /bin`
+	;;
+    OpenBSD)
+	CTYS_PING=`getPathName  $LINENO $BASH_SOURCE ERROR ping  /sbin`
+	;;
+    SunOS)
+	CTYS_PING=`getPathName  $LINENO $BASH_SOURCE ERROR ping  /usr/sbin`
+	;;
+    *)  
+ 	printERR $LINENO $BASH_SOURCE 1 "Unsupported OS=$MYOS"
+ 	printERR $LINENO $BASH_SOURCE 1 "Might fail, but continue..."
+	;;
+esac
+
 
 #DO NOT CHANGE!!!
 #Default order for ctys-tools.
 sortKey='-n';
-
+outform=TCP;
+_machine=1;
 for i in $*;do
     case $1 in
-#	'-q')shift;_quiet=1;;
-	'-X')CTRL_TERSE=1;shift;;
-	'-s')shift;_ssh=1;;
-	'-l')shift;_user=$1;shift;;
-	'-V')printVersion;exit 0;;
+	'-d')shift;shift;;
 	'-h')showToolHelp;exit 0;;
+	'-i')shift;raw=1;;
+	'-l')shift;_user=$1;shift;;
+	'-m')shift;outform=MACHINE;;
+	'-n')shift;_nocheck=1;;
+	'-r')shift;_recurse=1;;
+	'-s')shift;_ssh=1;;
+	'-t')shift;outform=TCP;_machine=0;;
+	'-V')printVersion;exit 0;;
+	'-X')shift;C_TERSE=1;_machine=0;;
     esac
 done
 
@@ -372,15 +475,14 @@ fi
 
 
 #OK-first let's expand ctys-groups
-printVerboseDebug ${DBG_LVL_UID} $LINENO $BASH_SOURCE "hostlist=$hostlist"
-hostlist=`expandGroups ${*}`
+printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "hostlist=$hostlist"
 
-#OK-second let's resolve ctys <machine-address>-es
-#printVerboseDebug ${DBG_LVL_UID} $LINENO $BASH_SOURCE "hostlist=$hostlist"
-#hostlist=`resolveMachineAddresses TCP ... ${hostlist}`
+if [ "$raw" == 1 ];then
+    inhostlist=$(expandGroups ${*});
+fi
 
-#NOW-That's it, this should be a pure TCP/IP-List
-#printVerboseDebug ${DBG_LVL_UID} $LINENO $BASH_SOURCE "hostlist=$hostlist"
+hostlist=$(fetchGroupMemberHosts ${*});
+printDBG $S_BIN ${D_UID} $LINENO $BASH_SOURCE "hostlist=$hostlist"
 
 if [ -n "$_dbfilepath" ];then
     if [ ! -d "$_dbfilepath" ];then
@@ -397,40 +499,133 @@ fi
 _STAT=6;
 _PING=6;
 _SSH=6;
-_TCP=25;
+_TCP=27;
+_TCP0=$_TCP;
 _MACH=;
-_FRM1="%-${_TCP}s %-${_PING}s %-${_SSH}s %${_MACH}s\n"
-
-
+_idx=4;
+_lvl=3;
+_FRM1="%-${_idx}s %-${_lvl}s%s %-${_TCP}s %-${_PING}s %-${_SSH}s %${_MACH}s\n" 
 _user=${_user:-$USER}
-echo
-echo -n "Check access permission by: \"ping"
-if [ -n "${_ssh}" ];then
-    echo -n "+ssh(SSO)\" "
-else
-    echo -n "\" "
-fi
-echo "  for USER=${_user}"
-echo
 
-printf "${_FRM1}"  "TCP/IP"  "ping"  "ssh"  "<machine-address>(ctys-vhost first-match!)"
-echo "----------------------------------------------------------------------------------"
-for i in ${hostlist};do
-    M=`ctys-vhost -o CTYS $i`
-    ping -c ${PCNT:-1} -w ${PTIME:-1} ${i} 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	if [ -n "${_ssh}" ];then
-	    ssh ${_user}@${i} echo 2>/dev/null >/dev/null
-	    if [ $? -eq 0 ];then
-		printf "${_FRM1}" "${i}" "+"  "+"  "${M}"
+
+if [ "${C_TERSE}" != 1 ];then
+    echo
+    echo -n "Check access permission by: \"ping"
+    if [ -n "${_ssh}" ];then
+	echo -n "+ssh(SSO)\" "
+    else
+	echo -n "\" "
+    fi
+    echo "  for USER=${_user}"
+    echo
+    if [ "$raw" == 1 ];then
+	echo "Input list is:"
+	echo
+	echo "------------->>"
+	echo "${inhostlist}"
+	echo "<<-------------"
+	echo
+    fi
+    printf "${_FRM1}" "idx" "lvl" "" "TCP/IP"  "ping"  "ssh"  "<machine-address>(ctys-vhost first-match!)"
+    echo "------------------------------------------------------------------------------------------"
+fi
+
+function processHostList () {
+    idx=${idx:-0};
+    local pidx=$idx;
+    local  _currec544=${1:-0};shift
+    local hlst=$*;
+    local _h=;
+    local _u=;
+    local _ia=;
+    local M=;
+    local res=;
+
+    if((CTYS_MAXRECURSE<_currec544));then
+	return 1
+    fi
+
+    for _ia in ${hlst};do
+	if [ "$_recurse" == 1 ];then
+	    local _memb=$(fetchGroupMemberHosts "${_ia}")
+	    if [ -n "${_memb// /}" ];then
+		pidx=*;
+		let idx--;
 	    else
-		printf "${_FRM1}" "${i}" "+"  "-"  "${M}"
+		pidx=$idx;
+	    fi
+	    if [ "$_currec544" == 0 ];then
+		_FRM1="%-${_idx}s %-${_lvl}s%s%-${_TCP}s %-${_PING}s %-${_SSH}s %${_MACH}s\n" 
+	    else
+		_FRM1="%-${_idx}s %-${_lvl}s%-$((1+2*_currec544))s%-$((_TCP0-2*_currec544))s %-${_PING}s %-${_SSH}s %${_MACH}s\n" 
+	    fi
+	fi
+
+	_h=${_ia#*@}
+	_u=${_ia%@*}
+	if [ "${_u}" == "${_ia}" ];then
+	    _u=${USER};
+	fi
+
+	if [ "$_machine" == 1 ];then
+	    M=`${MYCALLPATH}/ctys-vhost -o CTYS F:1:$_h E:28:1`
+	fi
+	if [ -n "${_nocheck}" ];then
+	    if [ "${C_TERSE}" != 1 ];then
+		printf "${_FRM1}"  "${pidx}" "${_currec544}" " "  "${_ia}" "-"  "?"  "${M}"
+	    else
+		case ${outform} in
+		    TCP)res="${res} ${_ia}";;
+		    MACHINE)res="${res} ${M}";;
+		esac
 	    fi
 	else
-            printf "${_FRM1}" "${i}" "+"  "?"  "${M}"
+	    ${CTYS_PING} -c ${PCNT:-1} -w ${PTIME:-1} ${_h} 2>/dev/null >/dev/null
+	    if [ $? -eq 0 ];then
+		if [ -n "${_ssh}" ];then
+		    _mtx=${_u:-$_user}@${_h}
+		    ssh ${_mtx} echo 2>/dev/null >/dev/null
+		    if [ $? -eq 0 ];then
+			if [ "${C_TERSE}" != 1 ];then
+			    printf "${_FRM1}" "${pidx}" "${_currec544}" " " "${_mtx}" "+"  "+"  "${M}"
+			else
+			    case ${outform} in
+				TCP)res="${res} ${_ia}";;
+				MACHINE)res="${res} ${M}";;
+			    esac
+			fi
+		    else
+			printf "${_FRM1}" "${pidx}" "${_currec544}" " "  "${_mtx}" "+"  "-"  "${M}"
+		    fi
+		else
+		    if [ "${C_TERSE}" != 1 ];then
+			printf "${_FRM1}" "${pidx}" "${_currec544}" " "  "${_ia}" "+"  "?"  "${M}"
+		    else
+			case ${outform} in
+			    TCP)res="${res} ${_ia}";;
+			    MACHINE)res="${res} ${M}";;
+			esac
+		    fi
+		fi
+	    else
+		printf "${_FRM1}" "${pidx}" "${_currec544}" " " "${_ia}" "-"  "?"  "${M}"
+	    fi
+	fi
+	let idx++;
+
+	if [ "$_recurse" == 1 ];then
+	    if [ -n "$_memb" -o "$_memb" == "$_ia" ];then
+		processHostList $((_currec544+1)) $(fetchGroupMemberHosts "${_ia}")
+	    fi
+	fi
+    done
+    if [ "${C_TERSE}" != 1 ];then
+	if((_currec544==0));then
+	    echo
 	fi
     else
-        printf "${_FRM1}"  "${i}" "-"  "?"  "${M}"
+	echo -n -e "${res}"
     fi
-done
-echo
+}
+
+processHostList 0 ${hostlist}
diff --git a/ctys/lib/help/help b/ctys/lib/help/help
--- a/ctys/lib/help/help
+++ b/ctys/lib/help/help
@@ -79,11 +79,11 @@ function functionHeaders () {
 	    fetchFileList
 
             for i in $x;do
-                cat $i|sed -n '/^#FUNCBEG#*$/,/^#FUNCEND#*$/!d;p'|\
+                cat $i|\
                     awk -v fn=$i '
                        BEGIN{n=0;line=0}
                        {line++;}
-                       $1~/^#NAME:/{n=1;getline;}
+                       $1~/^#NAME:/{n=1;getline;line++;}
                        n==1{
                          n=0;
                          printf("%-35s",$2);
@@ -180,7 +180,7 @@ function functionHeaders () {
 function printHelpEx () {
   local _lst=${@//[, ]/ }
 
-  printVerboseDebug ${DBG_LVL_UID} $LINENO $BASH_SOURCE "_lst=${_lst}"
+  printDBG $S_LIB ${D_UID} $LINENO $BASH_SOURCE "_lst=${_lst}"
 
   for i in $_lst;do
     KEY=`echo ${1}|tr '[:lower:]' '[:upper:]'`
@@ -202,28 +202,30 @@ function printHelpEx () {
      ALL|'*'|"")  #this is literally "all=='*'==''"
                   _printHelpEx|sed 's///';;
 
-               *) #this is any "*", which is not to be recognized a keyword,
+     *)           #this is any "*", which is not to be recognized a keyword,
                   #but expected to be "search-keyword", refer to manual.
-                  if [ -z "${_prea}" ];then printVersion;local _prea=1;fi
+  		  if [ -z "${_prea}" ];then printVersion;local _prea=1;fi
+		  doDebug $S_LIB $D_BULK $LINENO $BASH_SOURCE
+                  local D=$?
 
 		  echo 
 		  echo "SEARCH-KEYWORD-SECTION:regexpr< *$1.*>"
 		  echo 
-                  {
-                      if [ -z "${i//[^-]}" ];then _printHelpEx;
-                      else   cat ${MYOPTSFILES}; fi
-                  }|\
-                  awk -v _a=$i -v dbg=${DBG_LVL_HAYSTACK} -v d="${CTRL_VERBOSE}" -f ${_myLIBBASE_help}/helpEx1.awk;
+		  {
+                    if [ -z "${i//[^-]}" ];then _printHelpEx;
+                    else   cat ${MYOPTSFILES} 2>/dev/null; fi
+                   }|\
+                  awk -v _a=$i -v d="${D}" -f ${_myLIBBASE_help}/helpEx1.awk;
                   ;;
-    esac
-  done
+		esac
+		done
 }
 
 
 
 #FUNCBEG###############################################################
 #NAME:
-#  showHelp
+#  showToolHelp
 #
 #TYPE:
 #  bash-function
@@ -250,9 +252,18 @@ function showToolHelp () {
 	cat ${_myhlp}
     else
 	ABORT=1;
-	printERR $LINENO $BASH_SOURCE ${ABORT} "Missing help-file:\"${_myhlp}\""
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Missing online help-file:\"${_myhlp}\""
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Refer to the manual for required information"
 	gotoHell $ABORT
     fi
+    echo
+    echo "Due to reasons of consistency this version supports help by generated subchapters"
+    echo "from the User-Manual(meanwhile more than 400 pg.) only."
+    echo
+    echo "Some conversion problems from LaTex to ASC-II still lead to some unexpected"
+    echo "text changes. Particularly some difficulties with hyperlink marks still resist."
+    echo 
+    echo "Though when the online help seems to be too curious, refer to the PDF document."
 }
 
 #FUNCBEG###############################################################
@@ -275,13 +286,23 @@ function showToolHelp () {
 #
 #FUNCEND###############################################################
 function printVersion () {
-    if [ -n "$CTRL_TERSE" ];then
+    if [ -n "$C_TERSE" ];then
 	echo -n ${VERSION}
 	return
     fi
 
 
 cat <<EOF
+--------------------------------------------------------------------------
+
+UnifiedSessionsManager Copyright (C) 2007, 2008 Arno-Can Uestuensoez
+
+This program comes with ABSOLUTELY NO WARRANTY; for details  
+refer to provided documentation.
+This is free software, and you are welcome to redistribute it
+under certain conditions. For details refer to "GNU General Public 
+License - version 3" <http://www.gnu.org/licenses/>.
+
 --------------------------------------------------------------------------
 PROJECT          = ${FULLNAME} 
 --------------------------------------------------------------------------
@@ -295,7 +316,7 @@ DATE             = ${DATE}
 
 LOC              = ${LOC} CodeLines
 LOC-BARE         = ${LOCNET} BareCodeLines (no comments and empty lines)
-LOD              = ${LOD} DocLines
+LOD              = ${LOD} DocLines, include LaTeX-sources
 
 EOF
     cat ${MYCONFPATH}/versinfo.txt
diff --git a/ctys/plugins/HOSTs/X11/hook b/ctys/plugins/HOSTs/X11/hook
--- a/ctys/plugins/HOSTs/X11/hook
+++ b/ctys/plugins/HOSTs/X11/hook
@@ -21,27 +21,31 @@ X11_VERSTRING=;
 X11_STATE=DISABLED;
 X11SERVER_OPT=;
 X11VIEWER_OPT=;
-X11_PREREQ="X xterm";
+X11_PREREQ=;
 
 
 
 _myPKGNAME_X11="${BASH_SOURCE}"
-_myPKGVERS_X11="01.01.001a02"
+_myPKGVERS_X11="01.06.001a09"
 hookInfoAdd $_myPKGNAME_X11 $_myPKGVERS_X11
 _myPKGBASE_X11="${_myPKGNAME_X11%/hook}"
-_X11="${_myPKGBASE_X11}hook"
 
-CTRL_X11_DEFAULT="${CTRL_X11_DEFAULT:-bash -l -i}"
+X11_VERSTRING=${_myPKGVERS_X11};
 
-if [ -d "${HOME}/.ctys" -a -d "${HOME}/.ctys/cli" ];then
+
+C_X11_DEFAULT="${C_X11_DEFAULT:-bash -l -i}"
+
+if [ -d "${HOME}/.ctys" -a -d "${HOME}/.ctys/x11" ];then
     #Source pre-set environment from user
-    if [ -f "${HOME}/.ctys/cli/cli.conf" ];then
-	. "${HOME}/.ctys/cli/cli.conf"
+    if [ -f "${HOME}/.ctys/x11/x11.conf.${MYOS}" ];then
+	. "${HOME}/.ctys/x11/x11.conf.${MYOS}"
     fi
+fi
 
+if [ -d "${MYCONFPATH}" -a -d "${MYCONFPATH}/x11" ];then
     #Source pre-set environment from installation 
-    if [ -f "${MYCONFPATH}/conf/cli/cli.conf" ];then
-	. "${MYCONFPATH}/conf/cli/cli.conf"
+    if [ -f "${MYCONFPATH}/x11/x11.conf.${MYOS}" ];then
+	. "${MYCONFPATH}/x11/x11.conf.${MYOS}"
     fi
 fi
 
@@ -76,16 +80,16 @@ fi
 #
 #FUNCEND###############################################################
 function serverRequireX11 () {
-    printVerboseDebug ${DBG_LVL_HAYSTACK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
-    local _CS_SPLIT=`echo ${*}|sed -n 's/ConnectionForwarding/ServerOnly/p'`;
-    local _S=`getSessionType ${*}`;_S=${_S:-$CTRL_SESSIONTYPE};
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
+    local _CS_SPLIT=`echo ${*}|sed -n 's/CONNECTIONFORWARDING/SERVERONLY/p'`;
+    local _S=`getSessionType ${*}`;_S=${_S:-$C_SESSIONTYPE};
     local _A=`getActionResulting ${*}`;
     local _ret=1;
     local _res=;
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_S=\"${_S}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_A=\"${_A}\""
 
 
     #if split not supported server only could be used
@@ -97,8 +101,8 @@ function serverRequireX11 () {
  	_res="${*}";_ret=0;
     fi
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
     echo -n "${_res}";
     return ${_ret};  
 }
@@ -133,28 +137,28 @@ function serverRequireX11 () {
 #
 #FUNCEND###############################################################
 function clientRequireX11 () {
-    printVerboseDebug ${DBG_LVL_HAYSTACK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
-    local _CS_SPLIT=`echo ${*}|sed -n 's/ConnectionForwarding/1/p'`;
-    local _S=`getSessionType ${*}`;_S=${_S:-$CTRL_SESSIONTYPE};
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME \$@=$@"
+    local _CS_SPLIT=`echo ${*}|sed -n 's/CONNECTIONFORWARDING/1/p'`;
+    local _S=`getSessionType ${*}`;_S=${_S:-$C_SESSIONTYPE};
     local _A=`getActionResulting ${*}`;
     local _ret=1;
     local _res=;
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_S=\"${_S}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "_A=\"${_A}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_CS_SPLIT=\"${_CS_SPLIT}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_S=\"${_S}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "_A=\"${_A}\""
 
     #if split not supported server only could be used
     if [ -n "${_CS_SPLIT}" ];then
 	ABORT=1;
-	printERR $LINENO $BASH_SOURCE ${ABORT} "The console type X11 doe not support ConnectionForwarding"
+	printERR $LINENO $BASH_SOURCE ${ABORT} "The console type X11 doe not support CONNECTIONFORWARDING"
 	gotoHell ${ABORT}
     else
  	_res=;_ret=1;
     fi
 
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:_res=\"${_res}\""
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:_ret=\"${_ret}\""
     echo -n "${_res}";
     return ${_ret};  
 }
@@ -186,128 +190,183 @@ function clientRequireX11 () {
 #FUNCEND###############################################################
 function setVersionX11 () {
     local _checkonly=;
+    local _ret=0;
     if [ "$1" == "NOEXIT" ];then
 	local _checkonly=1;        
     fi
 
     local _verstrg=;
-    which X 2>/dev/null >/dev/null
-    if [ $? -ne 0 ];then
+    if [ -z "$X11EXE" ];then
 	ABORT=2
-	printERR $LINENO $_X11 ${ABORT} "Missing X for X11"
-	printERR $LINENO $_X11 ${ABORT} "can not find:"
-	printERR $LINENO $_X11 ${ABORT} " -> X"
-	printERR $LINENO $_X11 ${ABORT} ""
-	printERR $LINENO $_X11 ${ABORT} "Check your PATH"
-	printERR $LINENO $_X11 ${ABORT} " -> PATH=${PATH}"
-	printERR $LINENO $_X11 ${ABORT} ""
-	if [ "${CTRL_SESSIONTYPE}" == "X11" -a -z "${_checkonly}" ];then
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Missing X for X11"
+	printERR $LINENO $BASH_SOURCE ${ABORT} "can not find:"
+	printERR $LINENO $BASH_SOURCE ${ABORT} " -> X"
+	printERR $LINENO $BASH_SOURCE ${ABORT} ""
+	printERR $LINENO $BASH_SOURCE ${ABORT} "Check your PATH"
+	printERR $LINENO $BASH_SOURCE ${ABORT} " -> PATH=${PATH}"
+	printERR $LINENO $BASH_SOURCE ${ABORT} ""
+	if [ "${C_SESSIONTYPE}" == "X11" -a -z "${_checkonly}" ];then
 	    gotoHell ${ABORT}
 	else
 	    return ${ABORT}
 	fi
+	_ret=${ABORT};
     fi
 
 
 
-    _verstrg=`X -version 2>&1|egrep '(X Protocol Version)'`
+    _verstrg=`${X11EXE} -version 2>&1|awk '/(X Protocol Version)/{x="X"$4"R"$6"-"$8;gsub(",","",x);printf("%s",x);}'`
     if [ -z "${_verstrg}" ];then
-	printWNG $LINENO $_X11 0  "Unidentified Software Object - X11x"
-	printWNG $LINENO $_X11 0  "Scully is on the road..."
-  	_verstrg=GENERIC
+	printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11EXE} -version)\"` => [ `setSeverityColor ERR NOK` ]"
+	case ${MYOS} in
+	    SunOS)
+		case ${MYREL} in
+		    5.10)#asume for now on supported Solaris-5.10
+			_verstrg="X11R6";
+			printINFO 1 $LINENO $BASH_SOURCE 0  "Missing X-Version, guess for ${MYOS}/${MYREL}=>${_verstrg}"
+			;;
+		    5.1[0-9]*)#asume for now on 
+			_verstrg="X11R6x";
+			printINFO 1 $LINENO $BASH_SOURCE 0  "Missing X-Version, guess for ${MYOS}/${MYREL}=>${_verstrg}"
+			;;
+		    *)
+			printWNG 1 $LINENO $BASH_SOURCE 0  "Missing X-Version, guess for ${MYOS}/${MYREL}=>${_verstrg}"
+			_verstrg="X11Rx";
+			;;
+		esac
+		;;
+	    *)#hope
+		printWNG 1 $LINENO $BASH_SOURCE 0  "Missing X-Version, assume GENERIC"
+  		_verstrg=GENERIC
+		_ret=2;
+		;;
+	esac
 
+    else
+	printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11EXE} -version)\"` => [ `setSeverityColor INF OK` ]"
+	_ret=0;
     fi
-    X11_PREREQ=;
 
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_X11 "X11"
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_X11 "  _verstrg=${_verstrg}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "  _verstrg=${_verstrg}"
 
-    which X 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
+    if [ -n "$X11EXE" ];then
 	X11_PREREQ="${X11_PREREQ} X11:X";
+	_ret=0;
     else
 	X11_PREREQ="${X11_PREREQ} <disabled:X:X11>";
+	_ret=2;
     fi
 
 
-    which xterm 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	local _xtermver=`xterm -version`
-	X11_PREREQ="${X11_PREREQ} xterm-${_xtermver}";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:xterm>";
+    if [ -n "$X11XTERMEXE" ];then
+	local _xtermver=`callErrOutWrapper $LINENO $BASH_SOURCE ${X11XTERMEXE} -version `
+	if [ -n "$_xtermver" ];then
+	    X11_PREREQ="${X11_PREREQ} xterm-${_xtermver}";
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:xterm>";
+	    _ret=2;
+	fi
     fi
 
-
-    which mwm 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	X11_PREREQ="${X11_PREREQ} Motif:mwm";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:Motif:mwm>";
+    if [ -n "$X11MWMEXE" ];then
+	local _gdmver=`${X11MWMEXE} --help 2>&1|grep Another`
+	if [ -n "$_gdmver" ];then
+	    X11_PREREQ="${X11_PREREQ} Motif:mwm";
+	    printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11MWMEXE} --help)\"` => [ `setSeverityColor INF OK` ]"
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:Motif:mwm>";
+	    printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11MWMEXE} --help)\"` => [ `setSeverityColor ERR NOK` ]"
+	    _ret=2;
+	fi
     fi
 
-    local _GDM=`which gdm 2>/dev/null`
-    if [ $? -ne 0 ];then
-	_GDM=/usr/sbin/gdm
-    fi
-    if [ -f "${_GDM}" ];then
-	local _gdmver=`${_GDM} --version|awk '/GDM/{printf("gdm-%s",$2);}'`
-	X11_PREREQ="${X11_PREREQ} GNOME:${_gdmver// /_}:gdm";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:GNOME:gdm>";
-    fi
-
-    which gnome-terminal 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	X11_PREREQ="${X11_PREREQ} GNOME:gnome-terminal";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:GNOME:gnome-terminal>";
+    if [ -n "$X11GDMEXE" ];then
+	local _gdmver=`callErrOutWrapper $LINENO $BASH_SOURCE ${X11GDMEXE} --version|awk '/GDM/{printf("gdm-%s",$2);}' `
+	if [ -n "$_gdmver" ];then
+	    X11_PREREQ="${X11_PREREQ} GNOME:${_gdmver// /_}:gdm";
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:GNOME:gdm>";
+	    _ret=2;
+	fi
     fi
 
-    which kdm 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	X11_PREREQ="${X11_PREREQ} KDE:kdm";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:KDE:kdm>";
+    if [ -n "$X11GTERMEXE" ];then
+	local _gtermver=`callErrOutWrapper $LINENO $BASH_SOURCE ${X11GTERMEXE} --version|awk '/terminal/{printf("%s",$3);}' `
+	if [ -n "$_gtermver" ];then
+	    X11_PREREQ="${X11_PREREQ} GNOME:gnome-terminal${_gtermver}";
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:GNOME:gnome-terminal>";
+	    _ret=2;
+	fi
     fi
 
-    which fvwm 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-        local _fvwmver=`fvwm --version 2>&1 |awk '/Version/{printf("%s",$3);}'`
-	X11_PREREQ="${X11_PREREQ} FVWM:fvwm-${_fvwmver// /_}:fvwm";
-    else
-	X11_PREREQ="${X11_PREREQ} <disabled:FVWM:fvwm>";
+    if [ -n "$X11KDMEXE" ];then
+	local _kdmexe=`callErrOutWrapper $LINENO $BASH_SOURCE ${X11KDMEXE} --help `
+	if [ -n "$_kdmexe" ];then
+	    X11_PREREQ="${X11_PREREQ} KDE:kdm";
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:KDE:kdm>";
+	    _ret=2;
+	fi
     fi
 
-    which startxfce4 2>/dev/null >/dev/null
-    if [ $? -eq 0 ];then
-	local _xfcever=`xfce4-session --version|awk '/xfce4-session 4/{printf("%s-%s",$1,$2);}'`
-	X11_PREREQ="${X11_PREREQ} XFCE:${_xfcever// /_}:startxfce4+xfce4-session";
+    if [ -n "$X11FVWMEXE" ];then
+        local _fvwmver=`${X11FVWMEXE} --version 2>&1 |awk '/[^-][vV]ersion/{printf("%s",$3);}'`
+	if [ -n "$_fvwmver" ];then
+	    X11_PREREQ="${X11_PREREQ} FVWM:fvwm-${_fvwmver// /_}:fvwm";
+	    printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11FVWMEXE} -version)\"` => [ `setSeverityColor INF OK` ]"
+	    _ret=0;
+	else
+	    X11_PREREQ="${X11_PREREQ} <disabled:FVWM:fvwm>";
+	    printDBG $S_LIB ${D_SYS} $LINENO "$BASH_SOURCE" "$FUNCNAME:`setSeverityColor TRY \"call(${X11FVWMEXE} --version)\"` => [ `setSeverityColor ERR NOK` ]"
+	    _ret=2;
+	fi
+    fi
+
+    if [ -n "$X11XFCE4EXE" ];then
+#	local _xfcever=`xfce4-session --version|awk '/xfce4-session 4/{printf("%s-%s",$1,$2);}'`
+	local _xfcever=`callErrOutWrapper $LINENO $BASH_SOURCE ${X11XFCE4SESEXE} --version|awk '/xfce4-session 4/{printf("%s-%s",$1,$2);}' `
+	if [ -n "$_xfcever" ];then
+	    X11_PREREQ="${X11_PREREQ} XFCE:${_xfcever// /_}:startxfce4+xfce4-session";
+	else
+	    X11_PREREQ="${X11_PREREQ} XFCE:${_xfcever// /_}:startxfce+xfce-session";
+	fi
+	_ret=0;
     else
 	X11_PREREQ="${X11_PREREQ} <disabled:Xfce4:startxfce4>";
+	_ret=2;
     fi
 
     #currently somewhat restrictive to specific versions.
     case ${_verstrg} in
-	"X Protocol Version 11"*)
+	"X11R"*)
 	    X11_MAGIC=X11;
-	    X11_VERSTRING=${_verstrg};
 	    X11_STATE=ENABLED;
 	    X11SERVER_OPT=;
 	    X11VIEWER_OPT=;
+	    X11_PREREQ="HOST-CAPABILITY:X11-${X11_VERSTRING}-${MYARCH}%${_verstrg}-${MYARCH} ${X11_PREREQ}";
+	    _ret=0;
 	    ;;
-         *)
+        *)
 	    X11_MAGIC=X11G;
 	    X11SERVER_OPT=;
 	    X11VIEWER_OPT=;
+	    _ret=2;
 	    ;;
     esac
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11_MAGIC       = ${X11_MAGIC}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11_VERSTRING   = ${X11_VERSTRING}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11_STATE       = ${X11_STATE}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11_PREREQ      = ${X11_PREREQ}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11SERVER_OPT   = ${X11SERVER_OPT}"
-    printVerboseDebug ${DBG_LVL_UIE} $LINENO $_X11 "X11VIEWER_OPT   = ${X11VIEWER_OPT}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11_MAGIC       = ${X11_MAGIC}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11_VERSTRING   = ${X11_VERSTRING}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11_STATE       = ${X11_STATE}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11_PREREQ      = ${X11_PREREQ}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11SERVER_OPT   = ${X11SERVER_OPT}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "X11VIEWER_OPT   = ${X11VIEWER_OPT}"
+    return $_ret
 }
 
 
@@ -363,14 +422,9 @@ function noClientServerSplitSupportedMessageX11 () {
 #
 #FUNCEND###############################################################
 function clientServerSplitSupportedX11 () {
-    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $_X11 "$FUNCNAME $1"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME $1"
     case $1 in
 	CREATE)return 0;;
-#	CONNECT)return 0;;
-#	CANCEL)return 0;;
-#	SUSPEND)return 0;;
-#	RESUME)return 0;;
-#	SHIFT)return 0;;
     esac
     return 1;
 }
@@ -395,18 +449,17 @@ function clientServerSplitSupportedX11 () {
 #
 #FUNCEND###############################################################
 function enumerateMySessionsX11 () {
-    printVerboseDebug ${DBG_LVL_UID} $LINENO $_X11 "$FUNCNAME:\$@=${@}"
+    printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME:\$@=${@}"
 }
 
 
 
 
 #
-#Managed load of sub-packages which are required in almost any case.
+#Managed load of sub-packages gwhich are required in almost any case.
 #On-demand-loads will be performed within requesting action.
 #
 hookPackage "${_myPKGBASE_X11}/session"
-#hookPackage "${_myPKGBASE_X11}/enumerate"
 hookPackage "${_myPKGBASE_X11}/list"
 hookPackage "${_myPKGBASE_X11}/info"
 
@@ -434,21 +487,29 @@ hookPackage "${_myPKGBASE_X11}/info"
 #
 #FUNCEND###############################################################
 function handleX11 () {
-  printVerboseDebug ${DBG_LVL_UID} $LINENO $_X11 "${FUNCNAME}:$*"
+  printDBG $S_X11 ${D_BULK} $LINENO $BASH_SOURCE "${FUNCNAME}:$*"
   local OPMODE=$1;shift
   local ACTION=$1;shift
 
   case ${ACTION} in
 
       CREATE) 
-          hookPackage "${_myPKGBASE_X11}/create"
-          createConnectX11 ${OPMODE} ${ACTION} 
+	  case ${OPMODE} in
+              PROLOGUE)
+		  ;;
+              EPILOGUE)
+		  ;;
+	      CHECKPARAM|ASSEMBLE|EXECUTE)
+		  hookPackage "${_myPKGBASE_X11}/create"
+		  createConnectX11 ${OPMODE} ${ACTION} 
+		  ;;
+	  esac
           ;;
 
       *)
           #unknown
           ABORT=1;
-          printERR $LINENO $_X11 ${ABORT} "System Error, unsupported ACTION for X11:ACTION=${ACTION} OPMODE=${OPMODE}"
+          printERR $LINENO $BASH_SOURCE ${ABORT} "System Error, unsupported ACTION for X11:ACTION=${ACTION} OPMODE=${OPMODE}"
           ;;
   esac
 
@@ -479,20 +540,32 @@ function initX11 () {
   local _initConsequences=$1
   local ret=0;
 
-  printVerboseDebug ${DBG_LVL_SUPPORT} $LINENO $_X11 "$FUNCNAME ${_curInit}"
+  local _raise=$((INITSTATE<_curInit));
 
-  case $_curInit in
-      0);;#NOP - Done by shell
-      1)  #add own help to searchlist for options
-	  MYOPTSFILES="${MYOPTSFILES} ${MYPKGPATH}/HOSTs/X11/help/${MYLANG}/010_x11"
-          setVersionX11 $_initConsequences
-          ret=$?
-	  ;;
-      2);;#Curently nothing todo.
-      3);;#Curently nothing todo.
-      4);;#Curently nothing todo.
-      5);;#Curently nothing todo.
-  esac
+  printDBG $S_X11 ${D_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:${INITSTATE} -> ${_curInit} - ${_raise}"
+
+  if [ "$_raise" == "1" ];then
+      #for raise of INITSTATE do not touch the OS's decisions, just expand.
+
+      case $_curInit in
+	  0);;#NOP - Done by shell
+	  1)  #add own help to searchlist for options
+	      MYOPTSFILES="${MYOPTSFILES} ${MYHELPPATH}/010_x11"
+              setVersionX11 $_initConsequences
+              ret=$?
+	      ;;
+	  2);;
+	  3);;
+	  4);;
+	  5);;
+	  6);;
+      esac
+  else
+      case $_curInit in
+	  *);;
+      esac
+
+  fi
 
   return $ret
 }
